// GENERATED by scripts/gen-keyboard.mjs — do not edit.
//
// Each entry is a behaviour that packages/ui/src/components-keyboard.test.tsx actually asserts, with the keys that test presses. A component
// absent here has no keyboard test, and its page shows no keyboard section rather than inventing one.

export type KeyboardBehaviour = { behaviour: string; keys: string[] };

/** The test file these are derived from, shown on the page so a reader can go and check. */
export const KEYBOARD_SOURCE = "packages/ui/src/components-keyboard.test.tsx";

export const KEYBOARD: Record<string, KeyboardBehaviour[]> = {
  "alert-dialog": [
    {
      "behaviour": "opens with Enter and puts focus on the safe action, not the destructive one",
      "keys": [
        "Enter"
      ]
    },
    {
      "behaviour": "closes on Escape and returns focus to the trigger",
      "keys": [
        "Escape"
      ]
    }
  ],
  "checkbox": [
    {
      "behaviour": "Checkbox toggles with Space, not Enter",
      "keys": [
        "Enter",
        "Space",
        "Tab"
      ]
    }
  ],
  "color-picker": [
    {
      "behaviour": "adjusts the saturation/value square with the arrow keys (Shift = bigger step)",
      "keys": [
        "Arrow right",
        "Shift + Arrow right"
      ]
    },
    {
      "behaviour": "the hue rail is a named, keyboard-operable slider",
      "keys": [
        "Arrow right"
      ]
    },
    {
      "behaviour": "commits the hex field on Enter",
      "keys": [
        "Enter"
      ]
    }
  ],
  "context-menu": [
    {
      "behaviour": "walks items with the arrows, jumps with Home and End, finds one by typing, and closes on Escape",
      "keys": [
        "Arrow down",
        "End",
        "Home",
        "Escape"
      ]
    }
  ],
  "data-grid": [
    {
      "behaviour": "is a single tab stop: Tab enters on the first header, the next Tab leaves the grid",
      "keys": [
        "Tab"
      ]
    },
    {
      "behaviour": "moves between cells with the arrow keys, header row included, and stops at the edges",
      "keys": [
        "Arrow right",
        "Arrow down",
        "Arrow left",
        "Arrow up",
        "Tab"
      ]
    },
    {
      "behaviour": "Home / End go to the row ends; Ctrl+Home / Ctrl+End to the grid corners",
      "keys": [
        "Arrow down",
        "End",
        "Home",
        "Ctrl + End",
        "Ctrl + Home",
        "Tab"
      ]
    },
    {
      "behaviour": "remembers the active cell: leaving and re-entering the grid returns to it",
      "keys": [
        "Arrow down",
        "Arrow right",
        "Tab",
        "Shift + Tab"
      ]
    },
    {
      "behaviour": "sorts from the keyboard: Enter / Space on a sortable header",
      "keys": [
        "Enter",
        "Space",
        "Tab"
      ]
    },
    {
      "behaviour": "edits a cell from the keyboard: Enter to edit, Enter to commit, focus returns to the cell",
      "keys": [
        "Arrow down",
        "Enter",
        "Tab"
      ]
    },
    {
      "behaviour": "Escape cancels an edit without committing and returns focus to the cell",
      "keys": [
        "Arrow down",
        "Escape",
        "Tab"
      ]
    },
    {
      "behaviour": "Alt+Arrow reorders a column from its header, keeps focus on it, and announces the move",
      "keys": [
        "Alt + Arrow right",
        "Tab"
      ]
    },
    {
      "behaviour": "Shift+Arrow resizes a column from its header and announces the width",
      "keys": [
        "Arrow right",
        "Shift + Arrow right",
        "Shift + Arrow left",
        "Tab"
      ]
    },
    {
      "behaviour": "mirrors the arrow keys under RTL",
      "keys": [
        "Arrow left",
        "Arrow right",
        "Tab"
      ]
    },
    {
      "behaviour": "is off by default: no aria-multiselectable, no aria-selected, Shift+Arrow just moves",
      "keys": [
        "Arrow down",
        "Shift + Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "Shift+Arrow extends a rectangle from the anchor and reports it",
      "keys": [
        "Arrow down",
        "Shift + Arrow down",
        "Shift + Arrow right",
        "Tab"
      ]
    },
    {
      "behaviour": "shrinks when Shift moves back toward the anchor",
      "keys": [
        "Arrow down",
        "Shift + Arrow down",
        "Shift + Arrow up",
        "Tab"
      ]
    },
    {
      "behaviour": "a plain arrow key collapses the selection",
      "keys": [
        "Arrow down",
        "Shift + Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "Ctrl+A selects every cell; Escape clears it",
      "keys": [
        "Arrow down",
        "Escape",
        "Tab"
      ]
    },
    {
      "behaviour": "Shift+click extends from the previously active cell",
      "keys": [
        "Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "Ctrl+Space on a focused header selects its column",
      "keys": [
        "Ctrl + Space",
        "Tab"
      ]
    },
    {
      "behaviour": "Shift+Space on a cell selects its whole row",
      "keys": [
        "Arrow down",
        "Shift + Space",
        "Tab"
      ]
    },
    {
      "behaviour": "a plain click clears the selection",
      "keys": [
        "Arrow down",
        "Shift + Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "Ctrl+C copies the range as tab-separated values",
      "keys": [
        "Arrow down",
        "Shift + Arrow down",
        "Shift + Arrow right",
        "Tab"
      ]
    },
    {
      "behaviour": "Shift+click extends from the anchor even after it has scrolled out of the rendered window",
      "keys": [
        "Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "Ctrl+click adds a separate range and keeps the first, reporting both",
      "keys": [
        "Arrow down",
        "Shift + Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "Ctrl+click with nothing selected keeps the active cell as the first range",
      "keys": [
        "Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "Ctrl+Space is the keyboard way to add a range; Shift+arrows then extends the new one",
      "keys": [
        "Arrow down",
        "Ctrl + Space",
        "Arrow up",
        "Shift + Arrow down",
        "Shift + Arrow right",
        "Tab"
      ]
    },
    {
      "behaviour": "Ctrl+C copies every range, separated by a blank line",
      "keys": [
        "Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "re-sorting clears the selection (it refers to displayed rows)",
      "keys": [
        "Arrow down",
        "Shift + Arrow down",
        "Arrow up",
        "Enter",
        "Tab"
      ]
    },
    {
      "behaviour": "scrolls the target row into the rendered window and focuses it",
      "keys": [
        "Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "PageDown / Ctrl+End jump by a page and to the last row",
      "keys": [
        "Arrow down",
        "Page down",
        "Ctrl + End",
        "Tab"
      ]
    },
    {
      "behaviour": "stays reachable by Tab even after the active row scrolls out of the rendered window",
      "keys": [
        "Arrow down",
        "Ctrl + End",
        "Tab",
        "Shift + Tab"
      ]
    }
  ],
  "dialog": [
    {
      "behaviour": "opens from the keyboard and moves focus inside",
      "keys": [
        "Enter",
        "Tab"
      ]
    },
    {
      "behaviour": "traps Tab inside the dialog",
      "keys": [
        "Tab",
        "Shift + Tab"
      ]
    },
    {
      "behaviour": "closes on Escape and returns focus to the trigger",
      "keys": [
        "Escape"
      ]
    }
  ],
  "dropdown-menu": [
    {
      "behaviour": "opens with Enter, walks items with the arrow keys, closes with Escape",
      "keys": [
        "Enter",
        "Arrow down",
        "Arrow up",
        "Home",
        "Escape"
      ]
    }
  ],
  "file-upload": [
    {
      "behaviour": "has exactly one keyboard target — the Browse button — not a nested control or the hidden input",
      "keys": [
        "Tab"
      ]
    }
  ],
  "input": [
    {
      "behaviour": "are reached in source order by Tab and skipped when disabled",
      "keys": [
        "Tab",
        "Shift + Tab"
      ]
    },
    {
      "behaviour": "stay focusable and readable when read-only, and reject typing",
      "keys": [
        "Tab"
      ]
    }
  ],
  "input-otp": [
    {
      "behaviour": "fills one slot per keystroke and advances the caret",
      "keys": [
        "Tab"
      ]
    },
    {
      "behaviour": "clears the last filled slot on Backspace and steps the caret back",
      "keys": [
        "Backspace",
        "Tab"
      ]
    }
  ],
  "list": [
    {
      "behaviour": "a pressable row is a listitem containing a button, and Enter / Space activate it",
      "keys": [
        "Enter",
        "Space",
        "Tab"
      ]
    }
  ],
  "menubar": [
    {
      "behaviour": "opens a menu with Enter, moves into its items, and closes on Escape",
      "keys": [
        "Enter",
        "Arrow down",
        "Escape"
      ]
    }
  ],
  "modal": [
    {
      "behaviour": "opens from the keyboard, names itself, and closes on Escape without taking the action",
      "keys": [
        "Enter",
        "Escape"
      ]
    }
  ],
  "multi-select": [
    {
      "behaviour": "can be opened and an option chosen using only the keyboard",
      "keys": [
        "Enter",
        "Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "opens with a vertical arrow key as well as with Enter",
      "keys": [
        "Arrow down",
        "Tab"
      ]
    },
    {
      "behaviour": "closes with Escape and gives focus back to the combobox",
      "keys": [
        "Enter",
        "Escape",
        "Tab"
      ]
    },
    {
      "behaviour": "Backspace in the empty search field removes the last chip",
      "keys": [
        "Enter",
        "Backspace",
        "Tab"
      ]
    }
  ],
  "popover": [
    {
      "behaviour": "closes on Escape and returns focus to its trigger",
      "keys": [
        "Escape"
      ]
    }
  ],
  "radio-group": [
    {
      "behaviour": "is one tab stop; arrows move and select; Tab leaves the group",
      "keys": [
        "Arrow down",
        "Tab"
      ]
    }
  ],
  "select": [
    {
      "behaviour": "opens with Enter, walks options with the arrow keys and Home/End, and commits with Enter",
      "keys": [
        "Enter",
        "Arrow down",
        "End",
        "Home",
        "Tab"
      ]
    },
    {
      "behaviour": "jumps to an option by typing its first letter",
      "keys": [
        "Enter",
        "Tab"
      ]
    },
    {
      "behaviour": "closes with Escape without choosing, and hands focus back to the trigger",
      "keys": [
        "Enter",
        "Arrow down",
        "Escape",
        "Tab"
      ]
    }
  ],
  "sheet": [
    {
      "behaviour": "traps Tab inside the panel and closes on Escape, returning focus",
      "keys": [
        "Escape",
        "Tab"
      ]
    }
  ],
  "slider": [
    {
      "behaviour": "names the thumb (the role=slider element) from aria-label and moves with the arrow keys",
      "keys": [
        "Arrow right",
        "End",
        "Tab"
      ]
    },
    {
      "behaviour": "steps by a page with PageUp and PageDown, and clamps at the ends of the range",
      "keys": [
        "Page up",
        "Page down",
        "End",
        "Arrow up",
        "Tab"
      ]
    }
  ],
  "switch": [
    {
      "behaviour": "Switch toggles with Space and exposes role=switch",
      "keys": [
        "Space",
        "Tab"
      ]
    },
    {
      "behaviour": "a disabled Switch is skipped by Tab",
      "keys": [
        "Tab"
      ]
    }
  ],
  "tabs": [
    {
      "behaviour": "is a single tab stop; ArrowRight moves to and selects the next tab",
      "keys": [
        "Arrow right",
        "Tab"
      ]
    },
    {
      "behaviour": "supports Home and End",
      "keys": [
        "End",
        "Home",
        "Tab"
      ]
    },
    {
      "behaviour": "mirrors the arrow keys under RTL",
      "keys": [
        "Arrow left",
        "Arrow right",
        "Tab"
      ]
    }
  ],
  "textarea": [
    {
      "behaviour": "are reached in source order by Tab and skipped when disabled",
      "keys": [
        "Tab",
        "Shift + Tab"
      ]
    },
    {
      "behaviour": "stay focusable and readable when read-only, and reject typing",
      "keys": [
        "Tab"
      ]
    }
  ],
  "toggle": [
    {
      "behaviour": "toggles with Space and with Enter, and reports state through aria-pressed",
      "keys": [
        "Enter",
        "Space",
        "Tab"
      ]
    },
    {
      "behaviour": "a disabled Toggle is skipped by Tab and does not respond to keys",
      "keys": [
        "Tab"
      ]
    }
  ],
  "toggle-group": [
    {
      "behaviour": "is one tab stop, and the arrow keys move between items",
      "keys": [
        "Arrow right",
        "Arrow left",
        "Tab"
      ]
    },
    {
      "behaviour": "in multiple mode, Space presses items independently",
      "keys": [
        "Space",
        "Arrow right",
        "Tab"
      ]
    },
    {
      "behaviour": "in single mode, pressing one item releases the other",
      "keys": [
        "Space",
        "Arrow right",
        "Tab"
      ]
    }
  ],
  "tooltip": [
    {
      "behaviour": "appears on keyboard focus and describes its trigger",
      "keys": [
        "Tab"
      ]
    }
  ],
  "tour": [
    {
      "behaviour": "closes on Escape and returns focus to where it was",
      "keys": [
        "Escape"
      ]
    },
    {
      "behaviour": "keeps Tab inside the dialog while it is open",
      "keys": [
        "Tab"
      ]
    }
  ],
  "tree-view": [
    {
      "behaviour": "is one tab stop and moves with ArrowDown/ArrowUp",
      "keys": [
        "Arrow down",
        "Arrow up",
        "Tab"
      ]
    },
    {
      "behaviour": "ArrowRight expands, ArrowLeft collapses, and aria-expanded follows",
      "keys": [
        "Arrow right",
        "Arrow left",
        "Tab"
      ]
    },
    {
      "behaviour": "Enter selects the focused item",
      "keys": [
        "Arrow down",
        "Enter",
        "Tab"
      ]
    }
  ]
};
