/**
 * GENERATED by `pnpm gen:usage` from the kx-usage regions of the native packages' own compiled sources. Edit those, not this file.
 *
 * Each string below was extracted from a file its platform's CI compiles, so a snippet shown on a component
 * page cannot describe an API that no longer exists. `check:platform-code` prefers these over the
 * hand-written entries in platform-code.ts and fails if the two disagree.
 *
 * packages/ui-swiftui/Tests/KinetixUITests/Usage/UsageExamples.swift
 * packages/ui-compose/ui/src/test/kotlin/com/kinetixui/ui/usage/UsageExamplesTest.kt
 * packages/ui-flutter/test/usage/usage_examples_test.dart
 */
export const usageExamples: Record<string, Partial<Record<"swift" | "kotlin" | "dart", string>>> = {
  "badge-demo": {
    "swift": "            HStack(spacing: 8) {\n                KinetixBadge(\"Default\")\n                KinetixBadge(\"Secondary\", variant: .secondary)\n            }",
    "kotlin": "        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {\n            KinetixBadge(\"Default\")\n            KinetixBadge(\"Secondary\", variant = KinetixBadgeVariant.Secondary)\n        }",
    "dart": "        Row(\n          mainAxisSize: MainAxisSize.min,\n          children: const <Widget>[\n            KinetixBadge('Default'),\n            SizedBox(width: 8),\n            KinetixBadge('Secondary', variant: KinetixBadgeVariant.secondary),\n          ],\n        ),",
  },
  "button-demo": {
    "swift": "            KinetixButton(action: save) {\n                Text(\"Button\")\n            }",
    "kotlin": "        KinetixButton(onClick = save) {\n            Text(\"Button\")\n        }",
    "dart": "        KinetixButton(\n          onPressed: save,\n          child: const Text('Button'),\n        ),",
  },
  "switch-demo": {
    "swift": "            HStack {\n                KinetixSwitch(isOn: $airplane)\n                Text(\"Airplane mode\")\n            }",
    "kotlin": "        Row(verticalAlignment = Alignment.CenterVertically) {\n            KinetixSwitch(checked = airplane, onCheckedChange = { airplane = it })\n            Text(\"  Airplane mode\")\n        }",
    "dart": "        Row(\n          mainAxisSize: MainAxisSize.min,\n          children: <Widget>[\n            KinetixSwitch(value: airplane, onChanged: (bool v) => setState(() => airplane = v)),\n            const SizedBox(width: 8),\n            const Text('Airplane mode'),\n          ],\n        ),",
  },
};
