/**
 * GENERATED by `pnpm gen:usage` from the kx-usage regions of the packages' own compiled sources. Edit those, not this file.
 *
 * Each string below was extracted from a file its platform's CI compiles, so a snippet shown on a component
 * page cannot describe an API that no longer exists. `check:platform-code` prefers these over the
 * hand-written entries in platform-code.ts and fails if the two disagree.
 *
 * packages/ui/src/usage/icons.tsx
 * packages/ui-angular/src/usage/examples.ts
 * packages/ui-swiftui/Tests/KinetixUITests/Usage/UsageExamples.swift
 * packages/ui-compose/ui/src/test/kotlin/com/kinetixui/ui/usage/UsageExamplesTest.kt
 * packages/ui-flutter/test/usage/usage_examples_test.dart
 */
export const usageExamples: Record<string, Partial<Record<"react" | "angular" | "swift" | "kotlin" | "dart", string>>> = {
  "accordion-demo": {
    "angular": "@Component({\n  selector: 'app-accordion-demo',\n  imports: [KxAccordion, KxAccordionItem, KxAccordionTrigger, KxAccordionContent],\n  template: `\n    <kx-accordion type=\"single\" collapsible [(value)]=\"open\">\n      <kx-accordion-item value=\"shipping\">\n        <kx-accordion-trigger>When will my order ship?</kx-accordion-trigger>\n        <kx-accordion-content>Orders leave the warehouse within two working days.</kx-accordion-content>\n      </kx-accordion-item>\n      <kx-accordion-item value=\"returns\">\n        <kx-accordion-trigger>Can I return an item?</kx-accordion-trigger>\n        <kx-accordion-content>Yes, within 30 days, in its original packaging.</kx-accordion-content>\n      </kx-accordion-item>\n    </kx-accordion>\n  `,\n})\nexport class AccordionDemo {\n  open: readonly string[] = ['shipping'];\n}",
  },
  "alert-demo": {
    "angular": "<kx-alert>\n  <kx-alert-title>Heads up!</kx-alert-title>\n  <kx-alert-description>You can add components to your app using the CLI.</kx-alert-description>\n</kx-alert>",
  },
  "alert-dialog-demo": {
    "angular": "@Component({\n  selector: 'app-alert-dialog-demo',\n  imports: [KxButton, KxAlertDialog, KxDialogTrigger, KxAlertDialogContent, KxDialogHeader, KxDialogTitle, KxDialogDescription, KxDialogFooter, KxAlertDialogCancel, KxAlertDialogAction],\n  template: `\n    <kx-alert-dialog>\n      <button kxButton kxDialogTrigger variant=\"Outline\">Delete account</button>\n      <dialog kxAlertDialogContent>\n        <kx-dialog-header>\n          <h2 kxDialogTitle>Delete your account?</h2>\n          <p kxDialogDescription>Your projects and files are removed for everyone. This cannot be undone.</p>\n        </kx-dialog-header>\n        <kx-dialog-footer>\n          <button kxButton kxAlertDialogCancel variant=\"Outline\">Cancel</button>\n          <button kxButton kxAlertDialogAction variant=\"Destructive\" (click)=\"deleteAccount()\">Delete account</button>\n        </kx-dialog-footer>\n      </dialog>\n    </kx-alert-dialog>\n  `,\n})\nexport class AlertDialogDemo {\n  deleteAccount(): void {}\n}",
  },
  "app-bar-demo": {
    "angular": "@Component({\n  selector: 'app-app-bar-demo',\n  imports: [KxButton, KxAppBar, KxAppBarBrand, KxAppBarNav, KxAppBarLink, KxAppBarActions],\n  template: `\n    <header kxAppBar [sticky]=\"false\">\n      <a kxAppBarBrand href=\"/\">Acme</a>\n      <nav kxAppBarNav aria-label=\"Primary\">\n        <a kxAppBarLink href=\"/\" active>Overview</a>\n        <a kxAppBarLink href=\"/reports\">Reports</a>\n        <a kxAppBarLink href=\"/settings\">Settings</a>\n      </nav>\n      <div kxAppBarActions><button kxButton type=\"button\" size=\"sm\">New report</button></div>\n    </header>\n  `,\n})\nexport class AppBarDemo {}",
  },
  "aspect-ratio-demo": {
    "angular": "<kx-aspect-ratio [ratio]=\"16 / 9\">\n  <img src=\"/cover.jpg\" alt=\"\" />\n</kx-aspect-ratio>",
  },
  "avatar-demo": {
    "angular": "<kx-avatar>\n  <img kxAvatarImage src=\"/ada.jpg\" alt=\"Ada Lovelace\" />\n  <kx-avatar-fallback>AL</kx-avatar-fallback>\n</kx-avatar>",
  },
  "avatar-group-demo": {
    "angular": "<kx-avatar-group [max]=\"3\">\n  @for (person of team; track person.name) {\n    <kx-avatar>\n      <img kxAvatarImage [src]=\"person.photo\" [alt]=\"person.name\" />\n      <kx-avatar-fallback>{{ person.initials }}</kx-avatar-fallback>\n    </kx-avatar>\n  }\n</kx-avatar-group>",
  },
  "badge-demo": {
    "angular": "<kx-badge>Badge</kx-badge>",
    "swift": "HStack(spacing: 8) {\n    KinetixBadge(\"Default\")\n    KinetixBadge(\"Secondary\", variant: .secondary)\n}",
    "kotlin": "Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {\n    KinetixBadge(\"Default\")\n    KinetixBadge(\"Secondary\", variant = KinetixBadgeVariant.Secondary)\n}",
    "dart": "Row(\n  mainAxisSize: MainAxisSize.min,\n  children: const <Widget>[\n    KinetixBadge('Default'),\n    SizedBox(width: 8),\n    KinetixBadge('Secondary', variant: KinetixBadgeVariant.secondary),\n  ],\n),",
  },
  "banner-demo": {
    "angular": "@Component({\n  selector: 'app-banner-demo',\n  imports: [KxBanner],\n  template: `\n    @if (!dismissed) {\n      <kx-banner variant=\"warning\" sticky dismissible (dismiss)=\"dismissed = true\">\n        Scheduled maintenance begins at 02:00 UTC.\n        <button kxBannerAction type=\"button\" (click)=\"details()\">Read more</button>\n      </kx-banner>\n    }\n  `,\n})\nexport class BannerDemo {\n  dismissed = false;\n  details(): void {}\n}",
  },
  "breadcrumb-demo": {
    "angular": "@Component({\n  selector: 'app-breadcrumb-demo',\n  imports: [KxBreadcrumb, KxBreadcrumbList, KxBreadcrumbItem, KxBreadcrumbLink, KxBreadcrumbPage, KxBreadcrumbSeparator],\n  template: `\n    <nav kxBreadcrumb>\n      <ol kxBreadcrumbList>\n        <li kxBreadcrumbItem><a kxBreadcrumbLink href=\"/\">Home</a></li>\n        <li kxBreadcrumbSeparator></li>\n        <li kxBreadcrumbItem><a kxBreadcrumbLink href=\"/settings\">Settings</a></li>\n        <li kxBreadcrumbSeparator></li>\n        <li kxBreadcrumbItem><span kxBreadcrumbPage>Billing</span></li>\n      </ol>\n    </nav>\n  `,\n})\nexport class BreadcrumbDemo {}",
  },
  "button-demo": {
    "angular": "<button kxButton>Button</button>",
    "swift": "KinetixButton(action: save) {\n    Text(\"Button\")\n}",
    "kotlin": "KinetixButton(onClick = save) {\n    Text(\"Button\")\n}",
    "dart": "KinetixButton(\n  onPressed: save,\n  child: const Text('Button'),\n),",
  },
  "button-group-demo": {
    "angular": "@Component({\n  selector: 'app-button-group-demo',\n  imports: [KxButton, KxButtonGroup, KxButtonGroupText],\n  template: `\n    <div kxButtonGroup>\n      <kx-button-group-text>Qty</kx-button-group-text>\n      <button kxButton variant=\"Outline\" type=\"button\" aria-label=\"Decrease\">&minus;</button>\n      <button kxButton variant=\"Outline\" type=\"button\" aria-label=\"Increase\">+</button>\n    </div>\n  `,\n})\nexport class ButtonGroupDemo {}",
  },
  "card-demo": {
    "angular": "<kx-card>\n  <kx-card-header>\n    <kx-card-title>Create project</kx-card-title>\n    <kx-card-description>Deploy your new project in one click.</kx-card-description>\n  </kx-card-header>\n  <kx-card-content>\n    <label kxLabel for=\"name\">Name</label>\n    <input kxInput id=\"name\" placeholder=\"Name of your project\" />\n  </kx-card-content>\n  <kx-card-footer>\n    <button kxButton variant=\"Outline\">Cancel</button>\n    <button kxButton>Deploy</button>\n  </kx-card-footer>\n</kx-card>\n\n<!-- A card that is one action: kxCard on a real link (or button) gives it hover, pressed, focus and selected. -->\n<a kxCard href=\"#reports-q3\">\n  <kx-card-header>\n    <kx-card-title>Q3 report</kx-card-title>\n    <kx-card-description>Revenue, churn and cohort retention.</kx-card-description>\n  </kx-card-header>\n</a>",
  },
  "chart-demo": {
    "kotlin": "KinetixChart(\n    points = listOf(\n        KinetixChartPoint(\"Jan\", 186f),\n        KinetixChartPoint(\"Feb\", 305f),\n        KinetixChartPoint(\"Mar\", 237f),\n    ),\n    description = \"Monthly visitors: January 186, February 305, March 237\",\n)",
  },
  "checkbox-demo": {
    "angular": "<kx-checkbox [(checked)]=\"remember\" aria-label=\"Remember me\" />",
  },
  "circular-progress-demo": {
    "angular": "@Component({\n  selector: 'app-circular-progress-demo',\n  imports: [KxCircularProgress],\n  template: `\n    <kx-circular-progress [value]=\"72\" showValue [size]=\"56\" aria-label=\"Storage used\" />\n    <kx-circular-progress aria-label=\"Loading\" />\n  `,\n})\nexport class CircularProgressDemo {}",
  },
  "code-block-demo": {
    "angular": "@Component({\n  selector: 'app-code-block-demo',\n  imports: [KxCodeBlock],\n  template: ` <kx-code-block [code]=\"snippet\" filename=\"main.ts\" /> `,\n})\nexport class CodeBlockDemo {\n  readonly snippet = \"import { KxButton } from '@kinetixui/angular';\";\n}",
  },
  "collapsible-demo": {
    "angular": "@Component({\n  selector: 'app-collapsible-demo',\n  imports: [KxButton, KxCollapsible, KxCollapsibleTrigger, KxCollapsibleContent],\n  template: `\n    <kx-collapsible [(open)]=\"showAdvanced\">\n      <button kxButton kxCollapsibleTrigger variant=\"Ghost\" size=\"sm\">Advanced settings</button>\n      <kx-collapsible-content>\n        <p>Webhooks retry failed deliveries three times, an hour apart.</p>\n      </kx-collapsible-content>\n    </kx-collapsible>\n  `,\n})\nexport class CollapsibleDemo {\n  showAdvanced = false;\n}",
  },
  "description-list-demo": {
    "angular": "@Component({\n  selector: 'app-description-list-demo',\n  imports: [KxDescriptionList, KxDescriptionListItem],\n  template: `\n    <dl kxDescriptionList>\n      <div kxDescriptionListItem term=\"Status\">Active</div>\n      <div kxDescriptionListItem term=\"Plan\">Team &middot; annual</div>\n      <div kxDescriptionListItem term=\"Notes\" layout=\"stacked\">\n        Renews automatically unless cancelled 30 days before the term ends.\n      </div>\n    </dl>\n  `,\n})\nexport class DescriptionListDemo {}",
  },
  "dialog-demo": {
    "angular": "@Component({\n  selector: 'app-dialog-demo',\n  imports: [KxButton, KxInput, KxLabel, KxDialog, KxDialogTrigger, KxDialogContent, KxDialogHeader, KxDialogTitle, KxDialogDescription, KxDialogFooter, KxDialogClose],\n  template: `\n    <kx-dialog [(open)]=\"open\">\n      <button kxButton kxDialogTrigger variant=\"Outline\">Edit profile</button>\n      <dialog kxDialogContent>\n        <kx-dialog-header>\n          <h2 kxDialogTitle>Edit profile</h2>\n          <p kxDialogDescription>Make changes to your profile here.</p>\n        </kx-dialog-header>\n        <label kxLabel for=\"dialog-name\">Name</label>\n        <input kxInput id=\"dialog-name\" value=\"KinetixUI\" />\n        <kx-dialog-footer>\n          <button kxButton kxDialogClose variant=\"Outline\">Cancel</button>\n          <button kxButton type=\"button\" (click)=\"open = false\">Save changes</button>\n        </kx-dialog-footer>\n      </dialog>\n    </kx-dialog>\n  `,\n})\nexport class DialogDemo {\n  open = false;\n}",
  },
  "direction-provider-demo": {
    "angular": "<!-- No provider: the DOM's own dir attribute cascades, and Angular CDK's Directionality reads it. -->\n<div dir=\"rtl\">\n  <input kxInput placeholder=\"ابحث\" />\n  <button kxButton>حفظ</button>\n</div>",
    "swift": "// No provider to port: layout direction is an environment value, and every view below reads it.\nVStack {\n    KinetixInput(text: $query, placeholder: \"Search\")\n    KinetixButton(action: save) { Text(\"Save\") }\n}\n.environment(\\.layoutDirection, .rightToLeft)",
    "kotlin": "// No provider to port: layout direction is a CompositionLocal, and every composable below reads it.\nCompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl) {\n    Column {\n        KinetixInput(value = query, onValueChange = { query = it }, placeholder = \"Search\")\n        KinetixButton(onClick = save) { Text(\"Save\") }\n    }\n}",
    "dart": "// No provider to port: Directionality is inherited by every widget below it.\nDirectionality(\n  textDirection: TextDirection.rtl,\n  child: Column(\n    mainAxisSize: MainAxisSize.min,\n    children: <Widget>[\n      const KinetixInput(placeholder: 'Search'),\n      KinetixButton(onPressed: save, child: const Text('Save')),\n    ],\n  ),\n),",
  },
  "drawer-demo": {
    "angular": "@Component({\n  selector: 'app-drawer-demo',\n  imports: [KxButton, KxDrawer, KxDialogTrigger, KxDrawerContent, KxDialogHeader, KxDialogTitle, KxDialogDescription, KxDialogFooter, KxDialogClose],\n  template: `\n    <kx-drawer>\n      <button kxButton kxDialogTrigger variant=\"Outline\">Open drawer</button>\n      <dialog kxDrawerContent>\n        <kx-dialog-header>\n          <h2 kxDialogTitle>Move goal</h2>\n          <p kxDialogDescription>Set your daily activity goal.</p>\n        </kx-dialog-header>\n        <kx-dialog-footer>\n          <button kxButton kxDialogClose variant=\"Outline\">Cancel</button>\n          <button kxButton kxDialogClose>Submit</button>\n        </kx-dialog-footer>\n      </dialog>\n    </kx-drawer>\n  `,\n})\nexport class DrawerDemo {}",
  },
  "empty-demo": {
    "angular": "<kx-empty>\n  <kx-empty-header>\n    <kx-empty-media variant=\"icon\">📁</kx-empty-media>\n    <kx-empty-title>No projects yet</kx-empty-title>\n    <kx-empty-description>Create one to get started.</kx-empty-description>\n  </kx-empty-header>\n  <kx-empty-content>\n    <button kxButton>New project</button>\n  </kx-empty-content>\n</kx-empty>",
  },
  "fab-demo": {
    "angular": "@Component({\n  selector: 'app-fab-demo',\n  imports: [KxFab],\n  template: `\n    <button kxFab type=\"button\" aria-label=\"New message\">+</button>\n    <button kxFab extended type=\"button\">New message</button>\n  `,\n})\nexport class FabDemo {}",
  },
  "field-demo": {
    "angular": "<kx-field>\n  <label kxFieldLabel for=\"email\">Email</label>\n  <input kxInput id=\"email\" type=\"email\" aria-describedby=\"email-hint\" aria-invalid=\"true\" />\n  <p kxFieldDescription id=\"email-hint\">We only use this to sign you in.</p>\n  <kx-field-message variant=\"error\">Enter a valid address.</kx-field-message>\n</kx-field>",
  },
  "footer-demo": {
    "angular": "@Component({\n  selector: 'app-footer-demo',\n  imports: [KxFooter, KxFooterColumns, KxFooterColumn, KxFooterLink, KxFooterBottom],\n  template: `\n    <footer kxFooter>\n      <div kxFooterColumns>\n        <kx-footer-column title=\"Product\">\n          <a kxFooterLink href=\"/pricing\">Pricing</a>\n          <a kxFooterLink href=\"/changelog\">Changelog</a>\n        </kx-footer-column>\n        <kx-footer-column title=\"Company\">\n          <a kxFooterLink href=\"/about\">About</a>\n          <a kxFooterLink href=\"/careers\">Careers</a>\n        </kx-footer-column>\n      </div>\n      <div kxFooterBottom>\n        <span>&copy; 2026 Acme, Inc.</span>\n        <a kxFooterLink href=\"/privacy\">Privacy</a>\n      </div>\n    </footer>\n  `,\n})\nexport class FooterDemo {}",
  },
  "form-demo": {
    "angular": "@Component({\n  selector: 'app-signup',\n  imports: [ReactiveFormsModule, KxButton, KxField, KxFieldLabel, KxFieldMessage, KxInput],\n  template: `\n    <form [formGroup]=\"form\" (ngSubmit)=\"submit()\">\n      <kx-field>\n        <label kxFieldLabel for=\"email\">Email</label>\n        <input kxInput id=\"email\" formControlName=\"email\" [attr.aria-invalid]=\"email.invalid && email.touched\" />\n        @if (email.invalid && email.touched) {\n          <kx-field-message variant=\"error\">Enter a valid address.</kx-field-message>\n        }\n      </kx-field>\n      <button kxButton type=\"submit\" [disabled]=\"form.invalid\">Sign up</button>\n    </form>\n  `,\n})\nexport class SignupForm {\n  readonly form = new FormGroup({\n    email: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.email] }),\n  });\n  get email() {\n    return this.form.controls.email;\n  }\n  submit(): void {\n    if (this.form.valid) console.log(this.form.getRawValue());\n  }\n}",
  },
  "hover-card-demo": {
    "angular": "@Component({\n  selector: 'app-hover-card-demo',\n  imports: [KxHoverCard, KxHoverCardTrigger, KxHoverCardContent],\n  template: `\n    <kx-hover-card>\n      <a kxHoverCardTrigger href=\"/about\">@kinetixui</a>\n      <kx-hover-card-content>One token architecture, in motion across every platform.</kx-hover-card-content>\n    </kx-hover-card>\n  `,\n})\nexport class HoverCardDemo {}",
  },
  "icons-dismiss-icon": {
    "react": "{/* Default: lucide's X */}\n<Banner onDismiss={onDismiss}>Changes saved.</Banner>\n\n{/* Another lucide icon */}\n<Banner onDismiss={onDismiss} dismissIcon={<CircleX />}>\n  Changes saved.\n</Banner>\n\n{/* Your own icon: sized to 14px, coloured by the banner, named \"Dismiss\" */}\n<Banner onDismiss={onDismiss} dismissIcon={<CompanyCloseIcon />}>\n  Changes saved.\n</Banner>",
    "angular": "@Component({\n  selector: 'app-icons-dismiss-icon',\n  imports: [KxBanner],\n  template: `\n    <!-- Default: the built-in dismiss mark -->\n    <kx-banner dismissible (dismiss)=\"hide()\">Changes saved.</kx-banner>\n\n    <!-- Yours: any SVG or icon component carrying kxDismissIcon. The slot sizes it (14px), colours it\n         (currentColor) and names the button (\"Dismiss\"), so it needs no size, colour or aria. -->\n    <kx-banner dismissible (dismiss)=\"hide()\">\n      Changes saved.\n      <svg kxDismissIcon viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\n        <circle cx=\"12\" cy=\"12\" r=\"9\" />\n        <path d=\"m15 9-6 6M9 9l6 6\" />\n      </svg>\n    </kx-banner>\n  `,\n})\nexport class IconsDismissIconDemo {\n  hide(): void {}\n}",
    "swift": "VStack(spacing: 8) {\n    // Default: the xmark SF Symbol.\n    KinetixBanner(\"Changes saved.\", onDismiss: save)\n\n    // Another SF Symbol: tinted and sized by the banner, labelled \"Dismiss\".\n    KinetixBanner(\"Changes saved.\", onDismiss: save) {\n        Image(systemName: \"xmark.circle\")\n    }\n\n    // Your own view or asset: laid out in the same 14×14 frame.\n    KinetixBanner(\"Changes saved.\", onDismiss: save) {\n        Image(\"company-close\").resizable().scaledToFit()\n    }\n}",
    "kotlin": "// Default: Material's Close, drawn by KinetixUI.\nKinetixBanner(\"Changes saved.\", onDismiss = save)\n\n// Yours: any composable. The banner sizes it (14dp), tints it through LocalContentColor and names\n// the button \"Dismiss\" — so pass contentDescription = null.\nKinetixBanner(\n    \"Changes saved.\",\n    onDismiss = save,\n    dismissIcon = { Icon(imageVector = CompanyIcons.Close, contentDescription = null) },\n)",
    "dart": "// Default: Material's Icons.close.\nKinetixBanner('Changes saved.', onDismiss: save),\n\n// A Cupertino icon (add the cupertino_icons font package): sized to 14 and tinted by the banner.\nKinetixBanner('Changes saved.', onDismiss: save, dismissIcon: const Icon(CupertinoIcons.xmark_circle)),\n\n// Any widget — an SVG widget, your company's icon. Laid out at 14×14, named \"Dismiss\".\nKinetixBanner('Changes saved.', onDismiss: save, dismissIcon: const CompanyCloseIcon()),",
  },
  "icons-icon-only-button": {
    "react": "<Tooltip>\n  <TooltipTrigger asChild>\n    {/* size=\"icon\" keeps the svg visible and turns the text into the button's\n        screen-reader-only name: \"Delete draft, button\" */}\n    <Button size=\"icon\" variant=\"Ghost\" onClick={onDelete}>\n      <Trash2 />\n      <span>Delete draft</span>\n    </Button>\n  </TooltipTrigger>\n  <TooltipContent>Delete draft</TooltipContent>\n</Tooltip>",
  },
  "image-demo": {
    "angular": "@Component({\n  selector: 'app-image-demo',\n  imports: [KxImage],\n  template: `\n    <kx-image src=\"/cover.jpg\" alt=\"Harbour at dusk\" ratio=\"16:9\">\n      <span kxImageFallback>Unavailable</span>\n    </kx-image>\n  `,\n})\nexport class ImageDemo {}",
  },
  "inform-demo": {
    "angular": "@Component({\n  selector: 'app-inform-demo',\n  imports: [KxInform],\n  template: `\n    <kx-inform variant=\"success\">Your changes were saved.</kx-inform>\n    <kx-inform variant=\"error\" dismissible (dismiss)=\"hidden = true\">\n      We could not reach the server.\n      <button kxInformAction type=\"button\" (click)=\"retry()\">Try again</button>\n    </kx-inform>\n  `,\n})\nexport class InformDemo {\n  hidden = false;\n  retry(): void {}\n}",
  },
  "input-demo": {
    "angular": "<input kxInput type=\"email\" placeholder=\"Email\" />",
  },
  "input-group-demo": {
    "angular": "<kx-input-group>\n  <kx-input-group-text>https://</kx-input-group-text>\n  <input kxInputGroupInput aria-label=\"Website\" placeholder=\"kinetixui.com\" />\n</kx-input-group>\n<kx-input-group>\n  <kx-input-group-addon>$</kx-input-group-addon>\n  <input kxInputGroupInput aria-label=\"Amount\" placeholder=\"0.00\" inputmode=\"decimal\" />\n  <kx-input-group-text>USD</kx-input-group-text>\n</kx-input-group>\n<kx-input-group>\n  <input kxInputGroupInput aria-label=\"Invite link\" value=\"https://kinetixui.com/invite/7Q2X\" readonly />\n  <button kxInputGroupButton>Copy</button>\n</kx-input-group>",
  },
  "input-otp-demo": {
    "angular": "<kx-input-otp [(value)]=\"code\" [length]=\"6\" [groups]=\"[3, 3]\" aria-label=\"One-time code\" />",
  },
  "kbd-demo": {
    "angular": "<kbd kxKbdGroup>\n  <kbd kxKbd>Ctrl</kbd>\n  <kbd kxKbd>K</kbd>\n</kbd>",
  },
  "label-demo": {
    "angular": "<label kxLabel for=\"terms\">Accept terms and conditions</label>",
  },
  "list-demo": {
    "angular": "@Component({\n  selector: 'app-list-demo',\n  imports: [KxList, KxListItem],\n  template: `\n    <ul kxList>\n      <li kxListItem title=\"Billing\" description=\"Invoices and payment method\" pressable (select)=\"open('billing')\">\n        <span kxListTrailing>&rsaquo;</span>\n      </li>\n      <li kxListItem title=\"Members\" description=\"12 people\" pressable (select)=\"open('members')\">\n        <span kxListTrailing>&rsaquo;</span>\n      </li>\n      <li kxListItem title=\"Audit log\" description=\"Enterprise plans only\" disabled></li>\n    </ul>\n  `,\n})\nexport class ListDemo {\n  open(_section: string): void {}\n}",
  },
  "marquee-demo": {
    "angular": "@Component({\n  selector: 'app-marquee-demo',\n  imports: [KxMarquee, KxMarqueeContent],\n  template: `\n    <kx-marquee [durationSeconds]=\"24\" pauseOnHover>\n      <ng-template kxMarqueeContent>\n        <span>Ships to 48 countries</span>\n        <span>Free returns for 30 days</span>\n      </ng-template>\n    </kx-marquee>\n  `,\n})\nexport class MarqueeDemo {}",
  },
  "metric-demo": {
    "angular": "<kx-metric label=\"Revenue\" value=\"$48,120\" trend=\"up\" change=\"+12.4%\" />",
  },
  "modal-demo": {
    "angular": "@Component({\n  selector: 'app-modal-demo',\n  imports: [KxButton, KxModal, KxDialogTrigger],\n  template: `\n    <kx-modal type=\"Confirmation\" title=\"Publish this report?\" description=\"Everyone in the workspace can see it once it is published.\" (action)=\"publish()\">\n      <button kxButton kxDialogTrigger variant=\"Outline\">Publish</button>\n    </kx-modal>\n  `,\n})\nexport class ModalDemo {\n  publish(): void {}\n}",
  },
  "native-select-demo": {
    "angular": "<select kxNativeSelect aria-label=\"Country\">\n  <option value=\"pt\">Portugal</option>\n  <option value=\"es\">Spain</option>\n</select>",
  },
  "navigation-bar-demo": {
    "angular": "@Component({\n  selector: 'app-navigation-bar-demo',\n  imports: [KxButton, KxNavigationBar],\n  template: `\n    <header kxNavigationBar title=\"Inbox\" infoText=\"3 unread\" backButton (back)=\"goBack()\">\n      <button kxButton kxNavigationBarActions type=\"button\" variant=\"Ghost\" size=\"sm\">Edit</button>\n    </header>\n  `,\n})\nexport class NavigationBarDemo {\n  goBack(): void {}\n}",
  },
  "number-input-demo": {
    "angular": "<kx-number-input [(value)]=\"quantity\" [min]=\"1\" [max]=\"99\" aria-label=\"Quantity\" />",
  },
  "page-header-demo": {
    "angular": "@Component({\n  selector: 'app-page-header-demo',\n  imports: [KxButton, KxPageHeader],\n  template: `\n    <kx-page-header title=\"Billing\" description=\"Plan, invoices and payment method\">\n      <button kxButton kxPageHeaderActions type=\"button\" variant=\"Primary\">Upgrade</button>\n    </kx-page-header>\n  `,\n})\nexport class PageHeaderDemo {}",
  },
  "pagination-demo": {
    "angular": "@Component({\n  selector: 'app-pagination-demo',\n  imports: [KxPagination, KxPaginationContent, KxPaginationItem, KxPaginationLink, KxPaginationPrevious, KxPaginationNext, KxPaginationEllipsis],\n  template: `\n    <nav kxPagination>\n      <ul kxPaginationContent>\n        <li kxPaginationItem><a kxPaginationPrevious href=\"?page=1\">Previous</a></li>\n        <li kxPaginationItem><a kxPaginationLink href=\"?page=1\">1</a></li>\n        <li kxPaginationItem><a kxPaginationLink href=\"?page=2\" current>2</a></li>\n        <li kxPaginationItem><a kxPaginationLink href=\"?page=3\">3</a></li>\n        <li kxPaginationItem><kx-pagination-ellipsis /></li>\n        <li kxPaginationItem><a kxPaginationNext href=\"?page=3\">Next</a></li>\n      </ul>\n    </nav>\n  `,\n})\nexport class PaginationDemo {}",
  },
  "password-input-demo": {
    "angular": "<kx-password-input [(value)]=\"password\" aria-label=\"Password\" />",
  },
  "popover-demo": {
    "angular": "@Component({\n  selector: 'app-popover-demo',\n  imports: [KxButton, KxPopover, KxPopoverTrigger, KxPopoverContent],\n  template: `\n    <kx-popover>\n      <button kxButton kxPopoverTrigger variant=\"Outline\">Open popover</button>\n      <kx-popover-content labelledby=\"popover-demo-title\">\n        <p id=\"popover-demo-title\"><strong>Dimensions</strong></p>\n        <p>Set the dimensions for the layer.</p>\n      </kx-popover-content>\n    </kx-popover>\n  `,\n})\nexport class PopoverDemo {}",
  },
  "progress-demo": {
    "angular": "<kx-progress [value]=\"62\" aria-label=\"Upload progress\" />",
  },
  "quote-demo": {
    "angular": "<kx-quote author=\"Ada Lovelace\" authorTitle=\"Mathematician\">\n  The Analytical Engine weaves algebraic patterns.\n</kx-quote>",
  },
  "radio-group-demo": {
    "angular": "<kx-radio-group [(value)]=\"plan\" aria-label=\"Plan\">\n  <kx-radio value=\"free\">Free</kx-radio>\n  <kx-radio value=\"pro\">Pro</kx-radio>\n  <kx-radio value=\"team\">Team</kx-radio>\n</kx-radio-group>",
  },
  "rating-demo": {
    "angular": "<kx-rating [(value)]=\"rating\" aria-label=\"Rate this article\" />\n<kx-rating [value]=\"4\" readonly size=\"sm\" />",
  },
  "segmented-control-demo": {
    "angular": "<kx-segmented-control [(value)]=\"range\" aria-label=\"Range\">\n  <kx-segment value=\"7d\">7 days</kx-segment>\n  <kx-segment value=\"30d\">30 days</kx-segment>\n  <kx-segment value=\"90d\">90 days</kx-segment>\n</kx-segmented-control>",
  },
  "separator-demo": {
    "angular": "<kx-separator />\n<kx-separator orientation=\"vertical\" />",
  },
  "sheet-demo": {
    "angular": "@Component({\n  selector: 'app-sheet-demo',\n  imports: [KxButton, KxSheet, KxDialogTrigger, KxSheetContent, KxDialogHeader, KxDialogTitle, KxDialogDescription, KxDialogFooter, KxDialogClose],\n  template: `\n    <kx-sheet>\n      <button kxButton kxDialogTrigger variant=\"Outline\">Open</button>\n      <dialog kxSheetContent side=\"end\">\n        <kx-dialog-header>\n          <h2 kxDialogTitle>Edit profile</h2>\n          <p kxDialogDescription>Make changes to your profile here.</p>\n        </kx-dialog-header>\n        <kx-dialog-footer><button kxButton kxDialogClose>Done</button></kx-dialog-footer>\n      </dialog>\n    </kx-sheet>\n  `,\n})\nexport class SheetDemo {}",
  },
  "skeleton-demo": {
    "angular": "<kx-skeleton style=\"block-size: 1rem; inline-size: 60%\" />",
  },
  "slider-demo": {
    "angular": "<kx-slider [(value)]=\"volume\" [max]=\"100\" [step]=\"5\" aria-label=\"Volume\" />",
  },
  "spinner-demo": {
    "angular": "<kx-spinner size=\"lg\" label=\"Loading projects…\" />",
  },
  "stepper-demo": {
    "angular": "@Component({\n  selector: 'app-stepper-demo',\n  imports: [KxStepper],\n  template: ` <ol kxStepper [steps]=\"steps\" [current]=\"1\"></ol> `,\n})\nexport class StepperDemo {\n  readonly steps: KxStep[] = [\n    { label: 'Account', description: 'Email and password' },\n    { label: 'Workspace', description: 'Name and region' },\n    { label: 'Invite', description: 'Add your team' },\n  ];\n}",
  },
  "switch-demo": {
    "angular": "<kx-switch [(checked)]=\"notifications\" aria-label=\"Notifications\" />",
    "swift": "HStack {\n    KinetixSwitch(isOn: $airplane)\n    Text(\"Airplane mode\")\n}",
    "kotlin": "Row(verticalAlignment = Alignment.CenterVertically) {\n    KinetixSwitch(checked = airplane, onCheckedChange = { airplane = it })\n    Text(\"  Airplane mode\")\n}",
    "dart": "Row(\n  mainAxisSize: MainAxisSize.min,\n  children: <Widget>[\n    KinetixSwitch(value: airplane, onChanged: (bool v) => setState(() => airplane = v)),\n    const SizedBox(width: 8),\n    const Text('Airplane mode'),\n  ],\n),",
  },
  "tab-bar-demo": {
    "angular": "@Component({\n  selector: 'app-tab-bar-demo',\n  imports: [KxTabBar, KxTabBarItem],\n  template: `\n    <nav kxTabBar aria-label=\"Primary\">\n      <a kxTabBarItem href=\"/home\" active>\n        <svg kxTabBarIcon viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 11l8-7 8 7v9h-5v-6H9v6H4z\" fill=\"currentColor\" /></svg>\n        Home\n      </a>\n      <a kxTabBarItem href=\"/inbox\" badge=\"3\">\n        <svg kxTabBarIcon viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 5h16v14H4zM4 13h5l1 2h4l1-2h5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" /></svg>\n        Inbox\n      </a>\n      <a kxTabBarItem href=\"/account\">\n        <svg kxTabBarIcon viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"8\" r=\"4\" fill=\"currentColor\" /><path d=\"M4 21a8 8 0 0116 0\" fill=\"currentColor\" /></svg>\n        Account\n      </a>\n    </nav>\n  `,\n})\nexport class TabBarDemo {}",
  },
  "table-of-contents-demo": {
    "angular": "@Component({\n  selector: 'app-table-of-contents-demo',\n  imports: [KxTableOfContents],\n  template: ` <nav kxTableOfContents [items]=\"sections\" [(active)]=\"section\"></nav> `,\n})\nexport class TableOfContentsDemo {\n  readonly sections: KxTocItem[] = [\n    { id: 'install', label: 'Installation' },\n    { id: 'tokens', label: 'Load the tokens', level: 2 },\n    { id: 'usage', label: 'Usage' },\n  ];\n  section: string | null = 'install';\n}",
  },
  "tabs-demo": {
    "angular": "<kx-tabs [(value)]=\"tab\">\n  <kx-tab-list aria-label=\"Settings\">\n    <button kxTab value=\"account\">Account</button>\n    <button kxTab value=\"password\">Password</button>\n  </kx-tab-list>\n  <kx-tab-panel value=\"account\">Make changes to your account here.</kx-tab-panel>\n  <kx-tab-panel value=\"password\">Change your password here.</kx-tab-panel>\n</kx-tabs>",
  },
  "tag-demo": {
    "angular": "<kx-tag>Design</kx-tag>\n<kx-tag variant=\"outline\" removable (removed)=\"drop('Research')\">Research</kx-tag>",
  },
  "textarea-demo": {
    "angular": "<textarea kxTextarea rows=\"4\" placeholder=\"Type your message here.\"></textarea>",
  },
  "timeline-demo": {
    "angular": "@Component({\n  selector: 'app-timeline-demo',\n  imports: [KxTimeline, KxTimelineItem],\n  template: `\n    <ol kxTimeline>\n      <li kxTimelineItem title=\"Order placed\" description=\"12 March, 09:14\" status=\"success\"></li>\n      <li kxTimelineItem title=\"Dispatched\" description=\"12 March, 17:02\" status=\"success\"></li>\n      <li kxTimelineItem title=\"In transit\" description=\"Expected 15 March\" status=\"active\"></li>\n      <li kxTimelineItem title=\"Delivered\"></li>\n    </ol>\n  `,\n})\nexport class TimelineDemo {}",
  },
  "toggle-demo": {
    "angular": "<button kxToggle [(pressed)]=\"bold\" aria-label=\"Bold\">B</button>",
  },
  "toggle-group-demo": {
    "angular": "<kx-toggle-group [(value)]=\"marks\" aria-label=\"Text style\">\n  <kx-toggle-group-item value=\"bold\">B</kx-toggle-group-item>\n  <kx-toggle-group-item value=\"italic\">I</kx-toggle-group-item>\n  <kx-toggle-group-item value=\"underline\">U</kx-toggle-group-item>\n</kx-toggle-group>",
  },
  "tooltip-demo": {
    "angular": "@Component({\n  selector: 'app-tooltip-demo',\n  imports: [KxButton, KxTooltip, KxTooltipTrigger, KxTooltipContent],\n  template: `\n    <kx-tooltip>\n      <button kxButton kxTooltipTrigger variant=\"Outline\" type=\"button\">Hover</button>\n      <kx-tooltip-content>Add to library</kx-tooltip-content>\n    </kx-tooltip>\n  `,\n})\nexport class TooltipDemo {}",
  },
};
