/**
 * KinetixUI token build — runs Style Dictionary v4 once per theme.
 *   node style-dictionary/build.mjs        (via: pnpm build:tokens)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { getConfig } from './sd.config.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

for (const theme of ['light', 'dark']) {
  console.log(`\n▸ building tokens — ${theme}`);
  const sd = new StyleDictionary(getConfig(theme));
  await sd.cleanAllPlatforms();
  await sd.buildAllPlatforms();
}

// bundle the registry stylesheet: :root (light) + .dark + shadow/type extras
const web = `${ROOT}/packages/tokens/dist/web`;
writeFileSync(
  `${ROOT}/registry/kinetixui/globals.css`,
  `/* Generated by pnpm build:tokens — do not edit. :root = light, .dark = dark. */\n\n` +
    readFileSync(`${web}/globals.css`, 'utf8') +
    '\n' +
    readFileSync(`${web}/globals.dark.css`, 'utf8') +
    '\n' +
    readFileSync(`${web}/extras.css`, 'utf8') +
    '\n' +
    readFileSync(`${web}/extras.dark.css`, 'utf8'),
);

// derive tokens.js + tokens.d.ts from the generated tokens.ts so the npm
// package ships plain JS + types (apps in this repo can keep importing the .ts)
const tsSrc = readFileSync(`${web}/tokens.ts`, 'utf8');
const literal = tsSrc.slice(tsSrc.indexOf('{'), tsSrc.lastIndexOf('} as const;') + 1);
writeFileSync(
  `${web}/tokens.js`,
  '// Generated by pnpm build:tokens — do not edit.\n' +
    `export const tokens = ${literal};\nexport default tokens;\n`,
);
writeFileSync(
  `${web}/tokens.d.ts`,
  '// Generated by pnpm build:tokens — do not edit.\n' +
    `declare const tokens: ${literal};\n` +
    'export type Tokens = typeof tokens;\nexport { tokens };\nexport default tokens;\n',
);

console.log('\n✔ tokens built → packages/tokens/dist/{web,ios,android,flutter}');
console.log('✔ tokens.js + tokens.d.ts emitted for npm');
console.log('✔ registry/kinetixui/globals.css bundled (light + dark)');
