/**
 * Strata token build — runs Style Dictionary v4 once per theme.
 *   node style-dictionary/build.mjs        (via: pnpm build:tokens)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { getConfig } from './sd.config.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

for (const theme of ['light', 'dark']) {
  console.log(`\n▸ building tokens — ${theme}`);
  const sd = new StyleDictionary(getConfig(theme));
  await sd.cleanAllPlatforms();
  await sd.buildAllPlatforms();
}

// bundle the shadcn registry stylesheet: :root (light) + .dark in one file
const web = `${ROOT}/packages/tokens/dist/web`;
writeFileSync(
  `${ROOT}/registry/strata/globals.css`,
  `/* Generated by pnpm build:tokens — do not edit. :root = light, .dark = dark. */\n\n` +
    readFileSync(`${web}/globals.css`, 'utf8') +
    '\n' +
    readFileSync(`${web}/globals.dark.css`, 'utf8'),
);

console.log('\n✔ tokens built → packages/tokens/dist/{web,ios,android,flutter}');
console.log('✔ registry/strata/globals.css bundled (light + dark)');
