/**
 * Custom Style Dictionary v4 hooks (transforms) shared by all platforms.
 * Registered on the StyleDictionary class in sd.config.mjs before build.
 */

/** unitless dimension number -> "Npx" (web). Figma dimension tokens are plain numbers. */
export const dimensionToPx = {
  name: 'kinetix/dimension-px',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const n = Number(t.$value);
    if (!Number.isFinite(n)) return String(t.$value);
    return n === 0 ? '0' : `${n}px`;
  },
};

/** unitless dimension number -> "Ndp" for Android resource XML.
 *  (The built-in `android` transformGroup assumes rem input and multiplies by 16.) */
export const androidDimen = {
  name: 'kinetix/android-dimen',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const n = Number(t.$value);
    if (!Number.isFinite(n)) return String(t.$value);
    return n === 0 ? '0dp' : `${n}dp`;
  },
};

/** clean nested value-only TS module: { color: { blue: { "500": "#1b3c53" } } } */
export const tsNestedFormat = {
  name: 'kinetix/ts-nested',
  format: ({ dictionary }) => {
    const tree = {};
    for (const t of dictionary.allTokens) {
      let node = tree;
      for (const seg of t.path.slice(0, -1)) {
        node[seg] ??= {};
        node = node[seg];
      }
      node[t.path.at(-1)] = t.$value ?? t.value;
    }
    return (
      '// Do not edit directly — generated by Style Dictionary (pnpm build:tokens)\n\n' +
      `export const tokens = ${JSON.stringify(tree, null, 2)} as const;\n\n` +
      'export type Tokens = typeof tokens;\nexport default tokens;\n'
    );
  },
};

/** hex "#1b3c53" -> HSL channels "205 51% 22%" so Tailwind opacity modifiers
 *  work: `hsl(var(--primary) / <alpha-value>)`. Non-hex values pass through. */
function hexToHslChannels(hex) {
  let h = hex.replace('#', '').trim();
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let hue = 0;
  let sat = 0;
  if (max !== min) {
    const d = max - min;
    sat = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: hue = (g - b) / d + (g < b ? 6 : 0); break;
      case g: hue = (b - r) / d + 2; break;
      default: hue = (r - g) / d + 4;
    }
    hue /= 6;
  }
  return `${Math.round(hue * 360)} ${Math.round(sat * 100)}% ${Math.round(l * 100)}%`;
}

export const hslChannels = {
  name: 'kinetix/hsl-channels',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'color',
  transform: (t) => {
    const v = String(t.$value);
    return v.startsWith('#') ? hexToHslChannels(v) : v;
  },
};

/* ── shadow + typography → CSS (Finesse-UI-style token categories) ────────── */
const px = (v) => {
  const n = Number(v);
  return Number.isFinite(n) ? (n === 0 ? '0' : `${n}px`) : String(v);
};

/** DTCG shadow array -> `box-shadow` string */
function shadowToCss(value) {
  const layers = Array.isArray(value) ? value : [value];
  return layers
    .map((l) => `${px(l.offsetX)} ${px(l.offsetY)} ${px(l.blur)} ${px(l.spread)} ${l.color}`)
    .join(', ');
}

/** DTCG typography object -> CSS `font` shorthand (letterSpacing is applied
 *  separately via the Tailwind `fontSize` preset) */
function typographyToCss(v) {
  return `${v.fontWeight ?? 400} ${px(v.fontSize)}/${px(v.lineHeight)} ${v.fontFamily ?? 'sans-serif'}`;
}

/**
 * Emits the token categories `css/variables` can't express — `$type: shadow`
 * and `$type: typography` composites — as one flat `:root { … }` block.
 * Theme-independent, so only the light run writes it.
 */
export const extrasCssFormat = {
  name: 'kinetix/extras-css',
  format: ({ dictionary }) => {
    const shadows = [];
    const type = [];
    for (const t of dictionary.allTokens) {
      const v = t.$value ?? t.value;
      if (t.$type === 'shadow') shadows.push(`  --${t.path.join('-')}: ${shadowToCss(v)};`);
      else if (t.$type === 'typography') type.push(`  --text-${t.path.at(-1)}: ${typographyToCss(v)};`);
    }
    return (
      '/* Generated by Style Dictionary — shadow + typography composites. */\n\n' +
      ':root {\n' +
      shadows.join('\n') +
      (shadows.length && type.length ? '\n\n' : '') +
      type.join('\n') +
      '\n}\n'
    );
  },
};

/** strip a leading "color" segment and kebab-case the rest so CSS vars read
 *  --primary / --font-size-label-lg, not --color-primary / --fontSize-label-lg */
export const shadcnCssName = {
  name: 'kinetix/shadcn-css-name',
  type: 'name',
  transform: (t) => {
    const path = t.path[0] === 'color' ? t.path.slice(1) : t.path;
    return path
      .join('-')
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .toLowerCase();
  },
};
