/**
 * Custom Style Dictionary v4 hooks (transforms) shared by all platforms.
 * Registered on the StyleDictionary class in sd.config.mjs before build.
 */

/** unitless dimension number -> "Npx" (web). Figma dimension tokens are plain numbers. */
export const dimensionToPx = {
  name: 'kinetix/dimension-px',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const n = Number(t.$value);
    if (!Number.isFinite(n)) return String(t.$value);
    return n === 0 ? '0' : `${n}px`;
  },
};

/** unitless dimension number -> "Ndp" for Android resource XML.
 *  (The built-in `android` transformGroup assumes rem input and multiplies by 16.) */
export const androidDimen = {
  name: 'kinetix/android-dimen',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const n = Number(t.$value);
    if (!Number.isFinite(n)) return String(t.$value);
    return n === 0 ? '0dp' : `${n}dp`;
  },
};

/** clean nested value-only TS module: { color: { blue: { "500": "#1b3c53" } } } */
export const tsNestedFormat = {
  name: 'kinetix/ts-nested',
  format: ({ dictionary }) => {
    const tree = {};
    for (const t of dictionary.allTokens) {
      let node = tree;
      for (const seg of t.path.slice(0, -1)) {
        node[seg] ??= {};
        node = node[seg];
      }
      node[t.path.at(-1)] = t.$value ?? t.value;
    }
    return (
      '// Do not edit directly — generated by Style Dictionary (pnpm build:tokens)\n\n' +
      `export const tokens = ${JSON.stringify(tree, null, 2)} as const;\n\n` +
      'export type Tokens = typeof tokens;\nexport default tokens;\n'
    );
  },
};

/** hex "#1b3c53" -> HSL channels "205 51% 22%" so Tailwind opacity modifiers
 *  work: `hsl(var(--primary) / <alpha-value>)`. Non-hex values pass through. */
function hexToHslChannels(hex) {
  let h = hex.replace('#', '').trim();
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let hue = 0;
  let sat = 0;
  if (max !== min) {
    const d = max - min;
    sat = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: hue = (g - b) / d + (g < b ? 6 : 0); break;
      case g: hue = (b - r) / d + 2; break;
      default: hue = (r - g) / d + 4;
    }
    hue /= 6;
  }
  return `${Math.round(hue * 360)} ${Math.round(sat * 100)}% ${Math.round(l * 100)}%`;
}

export const hslChannels = {
  name: 'kinetix/hsl-channels',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'color',
  transform: (t) => {
    const v = String(t.$value);
    return v.startsWith('#') ? hexToHslChannels(v) : v;
  },
};

/* ── shadow + typography → CSS ───────────────────────────────────────────── */
const px = (v) => {
  const n = Number(v);
  return Number.isFinite(n) ? (n === 0 ? '0' : `${n}px`) : String(v);
};

/** DTCG shadow array -> `box-shadow` string */
function shadowToCss(value) {
  const layers = Array.isArray(value) ? value : [value];
  return layers
    .map((l) => `${px(l.offsetX)} ${px(l.offsetY)} ${px(l.blur)} ${px(l.spread)} ${l.color}`)
    .join(', ');
}

/** DTCG typography object -> CSS `font` shorthand (letterSpacing is applied
 *  separately via the Tailwind `fontSize` preset) */
function typographyToCss(v) {
  return `${v.fontWeight ?? 400} ${px(v.fontSize)}/${px(v.lineHeight)} ${v.fontFamily ?? 'sans-serif'}`;
}

/**
 * Emits the token categories `css/variables` can't express — `$type: shadow`
 * and `$type: typography` composites — as a flat `<selector> { … }` block.
 * The light run writes the full `:root` set; the dark run writes only the
 * theme-dependent focus rings under `.dark` (see sd.config.mjs `css-extras`).
 */
export const extrasCssFormat = {
  name: 'kinetix/extras-css',
  format: ({ dictionary, options }) => {
    const selector = options?.selector ?? ':root';
    const shadows = [];
    const type = [];
    for (const t of dictionary.allTokens) {
      const v = t.$value ?? t.value;
      if (t.$type === 'shadow') shadows.push(`  --${t.path.join('-')}: ${shadowToCss(v)};`);
      else if (t.$type === 'typography') type.push(`  --text-${t.path.at(-1)}: ${typographyToCss(v)};`);
    }
    return (
      '/* Generated by Style Dictionary — shadow + typography composites. */\n\n' +
      `${selector} {\n` +
      shadows.join('\n') +
      (shadows.length && type.length ? '\n\n' : '') +
      type.join('\n') +
      '\n}\n'
    );
  },
};

/* ── typography composites → mobile TextStyle emitters ──────────────────── */
const family1 = (f) => (f ?? 'Montserrat').split(',')[0].replace(/['"]/g, '').trim();
const num = (v) => Number(String(v).replace('px', '')) || 0;
const typographyTokens = (dictionary) =>
  dictionary.allTokens.filter((t) => t.$type === 'typography').map((t) => ({ name: t.path.at(-1), v: t.$value ?? t.value }));

const SWIFT_WEIGHT = { 400: '.regular', 500: '.medium', 600: '.semibold', 700: '.bold' };

/** SwiftUI — a KinetixTextStyle struct table (font + lineHeight + tracking) */
export const typeSwiftFormat = {
  name: 'kinetix/type-swift',
  format: ({ dictionary }) => {
    const rows = typographyTokens(dictionary)
      .map(({ name, v }) => {
        const w = SWIFT_WEIGHT[num(v.fontWeight)] ?? '.regular';
        return `    public static let ${camelize(name)} = KinetixTextStyle(font: .custom("${family1(v.fontFamily)}", size: ${num(v.fontSize)}).weight(${w}), lineHeight: ${num(v.lineHeight)}, tracking: ${num(v.letterSpacing)})`;
      })
      .join('\n');
    return (
      '//\n// KinetixType.swift — generated by Style Dictionary. Do not edit.\n//\n\nimport SwiftUI\n\n' +
      'public struct KinetixTextStyle {\n  public let font: Font\n  public let lineHeight: CGFloat\n  public let tracking: CGFloat\n}\n\n' +
      'public enum KinetixType {\n' +
      rows +
      '\n}\n'
    );
  },
};

/** Jetpack Compose — a KinetixType object of androidx TextStyle values */
export const typeComposeFormat = {
  name: 'kinetix/type-compose',
  format: ({ dictionary, options }) => {
    const rows = typographyTokens(dictionary)
      .map(
        ({ name, v }) =>
          `  val ${camelize(name)} = TextStyle(\n` +
          `    fontFamily = KinetixFontFamily,\n` +
          `    fontWeight = FontWeight.W${num(v.fontWeight) || 400},\n` +
          `    fontSize = ${num(v.fontSize)}.sp,\n` +
          `    lineHeight = ${num(v.lineHeight)}.sp,\n` +
          `    letterSpacing = ${num(v.letterSpacing)}.sp,\n  )`,
      )
      .join('\n');
    return (
      '// KinetixType.kt — generated by Style Dictionary. Do not edit.\n' +
      '// Define `KinetixFontFamily` once in your app, e.g.\n' +
      '//   val KinetixFontFamily = FontFamily(Font(R.font.montserrat), Font(R.font.montserrat_medium, FontWeight.Medium), …)\n\n' +
      `package ${options?.packageName ?? 'com.kinetixui.tokens'}\n\n` +
      'import androidx.compose.ui.text.TextStyle\n' +
      'import androidx.compose.ui.text.font.FontFamily\n' +
      'import androidx.compose.ui.text.font.FontWeight\n' +
      'import androidx.compose.ui.unit.sp\n\n' +
      'internal val KinetixFontFamily: FontFamily = FontFamily.Default // replace with your Montserrat FontFamily\n\n' +
      'object KinetixType {\n' +
      rows +
      '\n}\n'
    );
  },
};

/** Flutter — an AppText class of TextStyle values (height = lineHeight / size) */
export const typeDartFormat = {
  name: 'kinetix/type-dart',
  format: ({ dictionary }) => {
    const rows = typographyTokens(dictionary)
      .map(({ name, v }) => {
        const size = num(v.fontSize);
        const h = size ? (num(v.lineHeight) / size).toFixed(4) : '1.0';
        return (
          `  static const TextStyle ${camelize(name)} = TextStyle(\n` +
          `    fontFamily: '${family1(v.fontFamily)}',\n` +
          `    fontWeight: FontWeight.w${num(v.fontWeight) || 400},\n` +
          `    fontSize: ${size},\n` +
          `    height: ${h},\n` +
          `    letterSpacing: ${num(v.letterSpacing)},\n  );`
        );
      })
      .join('\n');
    return (
      '// app_text.dart — generated by Style Dictionary. Do not edit.\n\n' +
      "import 'package:flutter/painting.dart';\n\n" +
      'class AppText {\n  AppText._();\n\n' +
      rows +
      '\n}\n'
    );
  },
};

function camelize(s) {
  return s.replace(/[-_]([a-z0-9])/g, (_, c) => c.toUpperCase());
}

/* ── semantic colors → SwiftUI Color enum ───────────────────────────────── */
/** hex "#1b3c53" -> [0.106, 0.235, 0.325] (sRGB 0–1, 3dp — matches the
 *  UIColor output's precision). Non-hex values pass through as null. */
function hexToRgbFloats(hex) {
  let h = String(hex).replace('#', '').trim();
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  if (!/^[0-9a-fA-F]{6}$/.test(h)) return null;
  return [0, 2, 4].map((i) => Number((parseInt(h.slice(i, i + 2), 16) / 255).toFixed(3)));
}

/**
 * SwiftUI — a `Color`-valued enum of the semantic colour set, one file per
 * theme (`KinetixColorsSwiftUI` light / `…Dark` dark). Additive: the
 * existing `KinetixColors.swift` / `Theme.swift` (UIColor) are untouched.
 * `UIColor` is UIKit-only, so a SwiftUI package that must `swift build` on
 * macOS needs `Color`, not `UIColor` — hence this parallel output.
 */
export const swiftUIColorFormat = {
  name: 'kinetix/swiftui-color-enum',
  format: ({ dictionary, options }) => {
    const rows = dictionary.allTokens
      .filter((t) => t.$type === 'color')
      .map((t) => {
        const rgb = hexToRgbFloats(t.$value ?? t.value);
        if (!rgb) return null;
        const [r, g, b] = rgb;
        return `    public static let ${camelize(t.path.at(-1))} = Color(red: ${r}, green: ${g}, blue: ${b})`;
      })
      .filter(Boolean)
      .join('\n');
    return (
      '//\n// ' +
      `${options?.className ?? 'KinetixColorsSwiftUI'}` +
      ' — generated by Style Dictionary. Do not edit.\n//\n\nimport SwiftUI\n\n' +
      `public enum ${options?.className ?? 'KinetixColorsSwiftUI'} {\n` +
      rows +
      '\n}\n'
    );
  },
};

/* ── semantic colors → Flutter Color class (both passes) ────────────────── */
/** hex "#1b3c53" -> "Color(0xFF1B3C53)". Non-hex values pass through as null. */
function hexToDartColor(hex) {
  let h = String(hex).replace('#', '').trim();
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  if (!/^[0-9a-fA-F]{6}$/.test(h)) return null;
  return `Color(0xFF${h.toUpperCase()})`;
}

/**
 * Flutter — a `Color`-valued class of the semantic colour set, one file per
 * theme (`KinetixColorScheme` light / `KinetixColorSchemeDark` dark) for
 * the packages/ui-flutter widget library's `KinetixTheme`. Additive: the
 * existing `app_theme.dart` / `app_colors.dart` (light-only, class name
 * `KinetixTheme`/`KinetixColors`) are untouched — same split as the
 * SwiftUI `KinetixColorsSwiftUI` output. Dart `Color` is already the right
 * type for a Flutter widget, so unlike SwiftUI this is only about the
 * class name and getting a real dark pass.
 */
export const dartColorClassFormat = {
  name: 'kinetix/dart-color-class',
  format: ({ dictionary, options }) => {
    const cls = options?.className ?? 'KinetixColorScheme';
    const rows = dictionary.allTokens
      .filter((t) => t.$type === 'color')
      .map((t) => {
        const c = hexToDartColor(t.$value ?? t.value);
        return c ? `  static const ${camelize(t.path.at(-1))} = ${c};` : null;
      })
      .filter(Boolean)
      .join('\n');
    return (
      `//\n// ${cls} — generated by Style Dictionary. Do not edit.\n//\n\n` +
      "import 'dart:ui';\n\n" +
      `class ${cls} {\n  ${cls}._();\n\n` +
      rows +
      '\n}\n'
    );
  },
};

/* ── motion + scale (duration/easing/opacity/zIndex) → CSS + native ─────── */

/** DTCG cubicBezier array [x1,y1,x2,y2] -> CSS `cubic-bezier(...)` string.
 *  Web-only — native formats below want the raw four numbers instead. */
export const cssEasing = {
  name: 'kinetix/css-easing',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'cubicBezier',
  transform: (t) => `cubic-bezier(${t.$value.join(', ')})`,
};

const isMotionOrScale = (t) => ['duration', 'cubicBezier', 'number'].includes(t.$type);
/** the spatial scale — spacing + radius dimensions. Native-only: web already gets --spacing-* / --radius-*. */
const isSpatialScale = (t) => t.$type === 'dimension' && ['spacing', 'radius'].includes(t.path[0]);
/** group the four motion/scale primitive categories by their first path
 *  segment, e.g. `duration.fast` -> { category: 'duration', name: 'fast', v }.
 *  Duration values are DTCG strings ("200ms"); strip the unit for platforms
 *  that want a bare millisecond number. */
const motionMs = (v) => Number(String(v).replace('ms', ''));
const motionTokens = (dictionary) => {
  const groups = { duration: [], easing: [], opacity: [], zIndex: [], spacing: [], radius: [] };
  for (const t of dictionary.allTokens) {
    if (!isMotionOrScale(t) && !isSpatialScale(t)) continue;
    const category = t.path[0];
    if (!groups[category]) continue;
    groups[category].push({ name: t.path.at(-1), v: t.$value ?? t.value });
  }
  return groups;
};

/** SwiftUI — KinetixDuration (Swift Duration) / KinetixEasing (control-point
 *  tuples — no iOS-17 UnitCurve dependency) / KinetixOpacity / KinetixZIndex */
export const motionSwiftFormat = {
  name: 'kinetix/motion-swift',
  format: ({ dictionary }) => {
    const { duration, easing, opacity, zIndex, spacing, radius } = motionTokens(dictionary);
    const durationRows = duration
      .map(({ name, v }) => `    public static let ${camelize(name)} = Duration.milliseconds(${motionMs(v)})`)
      .join('\n');
    const easingRows = easing
      .map(({ name, v }) => `    public static let ${camelize(name)}: (Double, Double, Double, Double) = (${v.join(', ')})`)
      .join('\n');
    const opacityRows = opacity.map(({ name, v }) => `    public static let ${camelize(name)}: Double = ${v}`).join('\n');
    const zIndexRows = zIndex.map(({ name, v }) => `    public static let ${camelize(name)} = ${v}`).join('\n');
    const spacingRows = spacing.map(({ name, v }) => `    public static let space${name}: Double = ${Number(v)}`).join('\n');
    const radiusRows = radius.map(({ name, v }) => `    public static let ${camelize(name)}: Double = ${Number(v)}`).join('\n');
    return (
      '//\n// KinetixMotion.swift — generated by Style Dictionary. Do not edit.\n//\n\n' +
      'public enum KinetixDuration {\n' +
      durationRows +
      '\n}\n\n' +
      '/// (x1, y1, x2, y2) cubic-bezier control points.\n' +
      'public enum KinetixEasing {\n' +
      easingRows +
      '\n}\n\n' +
      'public enum KinetixOpacity {\n' +
      opacityRows +
      '\n}\n\n' +
      'public enum KinetixZIndex {\n' +
      zIndexRows +
      '\n}\n\n' +
      '/// Spatial scale in points — an 8-unit grid with a 4-unit half-step (see /docs/foundations).\n' +
      'public enum KinetixSpacing {\n' +
      spacingRows +
      '\n}\n\n' +
      'public enum KinetixRadius {\n' +
      radiusRows +
      '\n}\n'
    );
  },
};

/** Jetpack Compose — KinetixDuration (Int ms) / KinetixEasing (CubicBezierEasing)
 *  / KinetixOpacity (Float) / KinetixZIndex (Float, matches Modifier.zIndex) */
export const motionComposeFormat = {
  name: 'kinetix/motion-compose',
  format: ({ dictionary, options }) => {
    const { duration, easing, opacity, zIndex, spacing, radius } = motionTokens(dictionary);
    const durationRows = duration.map(({ name, v }) => `  const val ${camelize(name)} = ${motionMs(v)}`).join('\n');
    const easingRows = easing
      .map(({ name, v }) => `  val ${camelize(name)} = CubicBezierEasing(${v.map((n) => `${n}f`).join(', ')})`)
      .join('\n');
    const opacityRows = opacity.map(({ name, v }) => `  const val ${camelize(name)} = ${v}f`).join('\n');
    const zIndexRows = zIndex.map(({ name, v }) => `  const val ${camelize(name)} = ${v}f`).join('\n');
    const spacingRows = spacing.map(({ name, v }) => `  const val space${name} = ${Number(v)}f`).join('\n');
    const radiusRows = radius.map(({ name, v }) => `  const val ${camelize(name)} = ${Number(v)}f`).join('\n');
    return (
      '// KinetixMotion.kt — generated by Style Dictionary. Do not edit.\n\n' +
      `package ${options?.packageName ?? 'com.kinetixui.tokens'}\n\n` +
      'import androidx.compose.animation.core.CubicBezierEasing\n\n' +
      'object KinetixDuration {\n' +
      durationRows +
      '\n}\n\n' +
      'object KinetixEasing {\n' +
      easingRows +
      '\n}\n\n' +
      'object KinetixOpacity {\n' +
      opacityRows +
      '\n}\n\n' +
      'object KinetixZIndex {\n' +
      zIndexRows +
      '\n}\n\n' +
      '/** Spatial scale in dp (use `.dp`) — an 8-unit grid with a 4-unit half-step. */\n' +
      'object KinetixSpacing {\n' +
      spacingRows +
      '\n}\n\n' +
      'object KinetixRadius {\n' +
      radiusRows +
      '\n}\n'
    );
  },
};

/** Flutter — KinetixDuration (Duration) / KinetixEasing (Cubic Curve) /
 *  KinetixOpacity (double) / KinetixZIndex (double — advisory only; Flutter
 *  has no native z-index, stacking follows widget order in a Stack) */
export const motionDartFormat = {
  name: 'kinetix/motion-dart',
  format: ({ dictionary }) => {
    const { duration, easing, opacity, zIndex, spacing, radius } = motionTokens(dictionary);
    const durationRows = duration
      .map(({ name, v }) => `  static const Duration ${camelize(name)} = Duration(milliseconds: ${motionMs(v)});`)
      .join('\n');
    const easingRows = easing
      .map(({ name, v }) => `  static const Curve ${camelize(name)} = Cubic(${v.join(', ')});`)
      .join('\n');
    const opacityRows = opacity.map(({ name, v }) => `  static const double ${camelize(name)} = ${v};`).join('\n');
    const zIndexRows = zIndex.map(({ name, v }) => `  static const double ${camelize(name)} = ${v};`).join('\n');
    const spacingRows = spacing.map(({ name, v }) => `  static const double space${name} = ${Number(v)};`).join('\n');
    const radiusRows = radius.map(({ name, v }) => `  static const double ${camelize(name)} = ${Number(v)};`).join('\n');
    return (
      '// kinetix_motion.dart — generated by Style Dictionary. Do not edit.\n\n' +
      "import 'package:flutter/animation.dart';\n\n" +
      'class KinetixDuration {\n  KinetixDuration._();\n\n' +
      durationRows +
      '\n}\n\n' +
      'class KinetixEasing {\n  KinetixEasing._();\n\n' +
      easingRows +
      '\n}\n\n' +
      'class KinetixOpacity {\n  KinetixOpacity._();\n\n' +
      opacityRows +
      '\n}\n\n' +
      'class KinetixZIndex {\n  KinetixZIndex._();\n\n' +
      zIndexRows +
      '\n}\n\n' +
      '/// Spatial scale in logical pixels — an 8-unit grid with a 4-unit half-step.\n' +
      'class KinetixSpacing {\n  KinetixSpacing._();\n\n' +
      spacingRows +
      '\n}\n\n' +
      'class KinetixRadius {\n  KinetixRadius._();\n\n' +
      radiusRows +
      '\n}\n'
    );
  },
};

/** strip a leading "color" segment and kebab-case the rest so CSS vars read
 *  --primary / --font-size-label-lg, not --color-primary / --fontSize-label-lg */
export const cssVarName = {
  name: 'kinetix/css-var-name',
  type: 'name',
  transform: (t) => {
    const path = t.path[0] === 'color' ? t.path.slice(1) : t.path;
    return path
      .join('-')
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .toLowerCase();
  },
};
