/**
 * Custom Style Dictionary v4 hooks (transforms) shared by all platforms.
 * Registered on the StyleDictionary class in sd.config.mjs before build.
 */

/** unitless dimension number -> "Npx" (web). Figma dimension tokens are plain numbers. */
export const dimensionToPx = {
  name: 'strata/dimension-px',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const n = Number(t.$value);
    if (!Number.isFinite(n)) return String(t.$value);
    return n === 0 ? '0' : `${n}px`;
  },
};

/** unitless dimension number -> "Ndp" for Android resource XML.
 *  (The built-in `android` transformGroup assumes rem input and multiplies by 16.) */
export const androidDimen = {
  name: 'strata/android-dimen',
  type: 'value',
  transitive: true,
  filter: (t) => t.$type === 'dimension',
  transform: (t) => {
    const n = Number(t.$value);
    if (!Number.isFinite(n)) return String(t.$value);
    return n === 0 ? '0dp' : `${n}dp`;
  },
};

/** clean nested value-only TS module: { color: { blue: { "500": "#1b3c53" } } } */
export const tsNestedFormat = {
  name: 'strata/ts-nested',
  format: ({ dictionary }) => {
    const tree = {};
    for (const t of dictionary.allTokens) {
      let node = tree;
      for (const seg of t.path.slice(0, -1)) {
        node[seg] ??= {};
        node = node[seg];
      }
      node[t.path.at(-1)] = t.$value ?? t.value;
    }
    return (
      '// Do not edit directly — generated by Style Dictionary (pnpm build:tokens)\n\n' +
      `export const tokens = ${JSON.stringify(tree, null, 2)} as const;\n\n` +
      'export type Tokens = typeof tokens;\nexport default tokens;\n'
    );
  },
};

/** strip a leading "color" segment and kebab-case the rest so CSS vars read
 *  --primary / --font-size-label-lg, not --color-primary / --fontSize-label-lg */
export const shadcnCssName = {
  name: 'strata/shadcn-css-name',
  type: 'name',
  transform: (t) => {
    const path = t.path[0] === 'color' ? t.path.slice(1) : t.path;
    return path
      .join('-')
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .toLowerCase();
  },
};
