export { ShowcaseShell, type ShowcaseShellProps } from "./showcase-shell";
export {
  SpaceCanvas,
  hotspotName,
  type HotspotState,
  type PlanFeature,
  type PlanHotspot,
  type PlanLevel,
  type PlanRoom,
  type PlanShape,
  type PlanTone,
  type RoomAmbient,
  type SpaceCanvasProps,
  type SpacePlan,
} from "./space-canvas";
export {
  AttentionButton,
  Disclosure,
  Panel,
  RailGroup,
  RailItem,
  RailList,
  SpaceHeader,
  Stat,
  StateBadge,
  StateGlyph,
  SummaryChip,
  showcaseStateWord,
  type ShowcaseState,
} from "./primitives";
