//
// CreateThemeFixture — a KinetixUI Create theme.
//
// Generated by `kinetixui preset compose`. Edit the design in Create and re-export rather than
// editing this file: it is a rendering of a preset, not a source of one.
//
// Theme colour #c2410c · warm neutral · warm charts
//
// COLOURS ONLY. KinetixUI for Compose is themeable through `KinetixColors`, and this file carries
// every colour it has a field for. What this design can express and Compose cannot receive:
//
//   - radius (default) and surface treatment (soft). Compose reads these from
//     generated constants, not from a runtime theme, so nothing written here could override them.
//     Both apply on the web.
//   - `input` and `ring`. Create resolves both, and a preset can override either by
//     hand, but `KinetixColors` has no field for them.
//
// That is the complete list for this design. Nothing else was dropped.
//
// Separately, and not a Create limitation: `tertiary-foreground` is in the Kinetix
// token contract and in the SwiftUI theme, but Compose's `KinetixColors` does not expose it. Create
// does not model that token at all, so no preset can set it and nothing here is affected by it.
//
// A field written as `KinetixTokensLight.…` is one this design did not change, and it keeps
// following the library.
//

package com.kinetixui.create

import androidx.compose.ui.graphics.Color
import com.kinetixui.tokens.KinetixTheme as KinetixTokensLight
import com.kinetixui.tokens.KinetixThemeDark as KinetixTokensDark
import com.kinetixui.ui.KinetixColors

object CreateThemeFixture {
    /** Apply with `KinetixTheme(light = light, dark = dark) { … }`. */
    val light = KinetixColors(
        primary = Color(0xffc2410c),
        primaryForeground = Color(0xffffffff),
        action = Color(0xffc2410c),
        actionForeground = Color(0xffffffff),
        actionHover = Color(0xffc84716),
        actionPressed = Color(0xffcc4a1b),
        link = Color(0xffc2410c),
        focus = Color(0xffc2410c),
        brand = Color(0xffc2410c),
        brandForeground = Color(0xfffff2ed),
        secondary = KinetixTokensLight.colorSecondary,
        secondaryForeground = KinetixTokensLight.colorSecondaryForeground,
        destructive = KinetixTokensLight.colorDestructive,
        destructiveForeground = KinetixTokensLight.colorDestructiveForeground,
        foreground = Color(0xff0e0a06),
        background = Color(0xfffffffe),
        border = Color(0xffd6d0c9),
        muted = Color(0xfffcf6ee),
        mutedForeground = Color(0xff726c66),
        accent = Color(0xffffede8),
        accentForeground = Color(0xffc2410c),
        tertiary = KinetixTokensLight.colorTertiary,
        warning = KinetixTokensLight.colorWarning,
        warningForeground = KinetixTokensLight.colorWarningForeground,
        card = Color(0xfffffffe),
        cardForeground = Color(0xff0e0a06),
        success = KinetixTokensLight.colorSuccess,
        successForeground = KinetixTokensLight.colorSuccessForeground,
        info = KinetixTokensLight.colorInfo,
        infoForeground = KinetixTokensLight.colorInfoForeground,
        popover = Color(0xfffffffe),
        popoverForeground = Color(0xff0e0a06),
        chart = listOf(
            Color(0xffbd4049),
            Color(0xffe1791b),
            Color(0xff913900),
            Color(0xff848f00),
            Color(0xffd0a500),
        ),
    )

    val dark = KinetixColors(
        primary = Color(0xffe76438),
        primaryForeground = Color(0xff000000),
        action = Color(0xffe76438),
        actionForeground = Color(0xff000000),
        actionHover = Color(0xffd55326),
        actionPressed = Color(0xffcb4919),
        link = Color(0xffe76438),
        focus = Color(0xffe76438),
        brand = Color(0xffc2410c),
        brandForeground = Color(0xfffff2ed),
        secondary = KinetixTokensDark.colorSecondary,
        secondaryForeground = KinetixTokensDark.colorSecondaryForeground,
        destructive = KinetixTokensDark.colorDestructive,
        destructiveForeground = KinetixTokensDark.colorDestructiveForeground,
        foreground = Color(0xfffbf4ed),
        background = Color(0xff110c08),
        border = Color(0xff4c4741),
        muted = Color(0xff2a2520),
        mutedForeground = Color(0xffaaa39d),
        accent = Color(0xff2f1811),
        accentForeground = Color(0xffe76438),
        tertiary = KinetixTokensDark.colorTertiary,
        warning = KinetixTokensDark.colorWarning,
        warningForeground = KinetixTokensDark.colorWarningForeground,
        card = Color(0xff1e1a15),
        cardForeground = Color(0xfffbf4ed),
        success = KinetixTokensDark.colorSuccess,
        successForeground = KinetixTokensDark.colorSuccessForeground,
        info = KinetixTokensDark.colorInfo,
        infoForeground = KinetixTokensDark.colorInfoForeground,
        popover = Color(0xff1e1a15),
        popoverForeground = Color(0xfffbf4ed),
        chart = listOf(
            Color(0xfff17074),
            Color(0xffca6800),
            Color(0xffff996a),
            Color(0xff707900),
            Color(0xfff6c835),
        ),
    )
}
