// KinetixType.kt — generated by Style Dictionary. Do not edit.
// Define `KinetixFontFamily` once in your app, e.g.
//   val KinetixFontFamily = FontFamily(Font(R.font.montserrat), Font(R.font.montserrat_medium, FontWeight.Medium), …)

package com.kinetixui.tokens

import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

internal val KinetixFontFamily: FontFamily = FontFamily.Default // replace with your Montserrat FontFamily

object KinetixType {
  val displayLg = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W500,
    fontSize = 57.sp,
    lineHeight = 64.sp,
    letterSpacing = -0.25.sp,
  )
  val displayMd = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W500,
    fontSize = 45.sp,
    lineHeight = 52.sp,
    letterSpacing = 0.sp,
  )
  val displaySm = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W400,
    fontSize = 36.sp,
    lineHeight = 44.sp,
    letterSpacing = 0.sp,
  )
  val headlineLg = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W600,
    fontSize = 32.sp,
    lineHeight = 40.sp,
    letterSpacing = 0.sp,
  )
  val headlineMd = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W400,
    fontSize = 28.sp,
    lineHeight = 36.sp,
    letterSpacing = 0.sp,
  )
  val headlineSm = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W400,
    fontSize = 24.sp,
    lineHeight = 32.sp,
    letterSpacing = 0.sp,
  )
  val titleLg = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W400,
    fontSize = 22.sp,
    lineHeight = 28.sp,
    letterSpacing = 0.sp,
  )
  val titleMd = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W500,
    fontSize = 16.sp,
    lineHeight = 24.sp,
    letterSpacing = 0.15.sp,
  )
  val titleSm = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W500,
    fontSize = 14.sp,
    lineHeight = 20.sp,
    letterSpacing = 0.1.sp,
  )
  val titleDialog = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W600,
    fontSize = 18.sp,
    lineHeight = 24.sp,
    letterSpacing = 0.sp,
  )
  val labelLg = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W500,
    fontSize = 14.sp,
    lineHeight = 20.sp,
    letterSpacing = 0.1.sp,
  )
  val labelMd = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W500,
    fontSize = 12.sp,
    lineHeight = 16.sp,
    letterSpacing = 0.5.sp,
  )
  val labelSm = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W500,
    fontSize = 11.sp,
    lineHeight = 16.sp,
    letterSpacing = 0.5.sp,
  )
  val bodyLg = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W400,
    fontSize = 16.sp,
    lineHeight = 24.sp,
    letterSpacing = 0.5.sp,
  )
  val bodyMd = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W400,
    fontSize = 14.sp,
    lineHeight = 20.sp,
    letterSpacing = 0.25.sp,
  )
  val bodySm = TextStyle(
    fontFamily = KinetixFontFamily,
    fontWeight = FontWeight.W400,
    fontSize = 12.sp,
    lineHeight = 16.sp,
    letterSpacing = 0.sp,
  )
}
