// KinetixMotion.kt — generated by Style Dictionary. Do not edit.

package com.kinetixui.tokens

import androidx.compose.animation.core.CubicBezierEasing

object KinetixDuration {
  const val fast = 200
  const val base = 300
  const val slow = 500
  const val slower = 1000
}

object KinetixEasing {
  val linear = CubicBezierEasing(0f, 0f, 1f, 1f)
  val standard = CubicBezierEasing(0.4f, 0f, 0.2f, 1f)
}

object KinetixOpacity {
  const val hidden = 0f
  const val disabled = 0.5f
  const val muted = 0.7f
  const val visible = 1f
}

object KinetixZIndex {
  const val base = 0f
  const val raised = 1f
  const val docked = 10f
  const val focus = 20f
  const val sticky = 40f
  const val overlay = 50f
}
