package com.kinetixui.ui

import androidx.compose.material3.Text
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.test.junit4.v2.createComposeRule
import com.kinetixui.create.CreateThemeFixture
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Custom themes, and the promise that the old call still means what it meant.
 *
 * `com.kinetixui.create.CreateThemeFixture` is generated by the `compose` exporter in
 * `packages/create-theme` and committed so this target compiles it — which is the only place in the repo
 * that the exporter's output is type-checked against the real `KinetixColors` constructor. A drift test
 * on the TypeScript side fails if the committed file stops matching the exporter.
 *
 * Compiling is not enough on its own, though: a generated theme that compiles and then does not reach
 * the components is a worse outcome than one that fails to build. So these read the value back out of
 * the composition the way a component does, through `KinetixColorScheme.current`.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class CustomThemeTest {
    @get:Rule
    val compose = createComposeRule()

    /** Read `KinetixColorScheme.current` from inside a composition, the way a `Kinetix*` component does. */
    private fun colorsUnder(content: @androidx.compose.runtime.Composable (@androidx.compose.runtime.Composable () -> Unit) -> Unit): KinetixColors {
        lateinit var seen: KinetixColors
        compose.setContent {
            content {
                seen = KinetixColorScheme.current
                Text("probe")
            }
        }
        return seen
    }

    // MARK: a custom theme actually installs

    @Test
    fun custom_light_colors_reach_the_components() {
        val colors = colorsUnder { body ->
            KinetixTheme(darkTheme = false, light = CreateThemeFixture.light, dark = CreateThemeFixture.dark) { body() }
        }
        assertEquals(CreateThemeFixture.light.action, colors.action)
        assertEquals(CreateThemeFixture.light.background, colors.background)
        assertEquals(CreateThemeFixture.light.chart, colors.chart)
    }

    @Test
    fun custom_dark_colors_reach_the_components() {
        val colors = colorsUnder { body ->
            KinetixTheme(darkTheme = true, light = CreateThemeFixture.light, dark = CreateThemeFixture.dark) { body() }
        }
        assertEquals(CreateThemeFixture.dark.action, colors.action)
        assertEquals(CreateThemeFixture.dark.background, colors.background)
    }

    @Test
    fun light_and_dark_are_actually_different_sets() {
        // Guards the shape of the test as much as the theme: if both branches returned the same object,
        // the two assertions above would pass while proving nothing.
        assertNotEquals(CreateThemeFixture.light.background, CreateThemeFixture.dark.background)
        assertNotEquals(CreateThemeFixture.light.foreground, CreateThemeFixture.dark.foreground)
    }

    @Test
    fun the_fixture_is_a_real_custom_theme_not_the_shipped_one() {
        // The design behind the fixture is a warm neutral with an orange brand, so its action colour and
        // its surfaces must differ from what ships. Otherwise "custom colours install" is untested.
        assertNotEquals(LightKinetixColors.action, CreateThemeFixture.light.action)
        assertNotEquals(LightKinetixColors.background, CreateThemeFixture.light.background)
    }

    // MARK: the existing call is unchanged

    @Test
    fun the_default_call_still_resolves_to_the_shipped_light_set() {
        val colors = colorsUnder { body -> KinetixTheme(darkTheme = false) { body() } }
        assertEquals(LightKinetixColors, colors)
    }

    @Test
    fun the_default_call_still_resolves_to_the_shipped_dark_set() {
        val colors = colorsUnder { body -> KinetixTheme(darkTheme = true) { body() } }
        assertEquals(DarkKinetixColors, colors)
    }

    @Test
    fun the_bare_trailing_lambda_form_still_compiles_and_themes() {
        // `KinetixTheme { … }` is the call in every preview and every consumer. Adding parameters with
        // defaults keeps it valid; adding an OVERLOAD would have made it ambiguous, which is why the
        // parameters went on the existing function instead.
        val colors = colorsUnder { body -> KinetixTheme { body() } }
        assertNotEquals(Color.Unspecified, colors.action)
    }

    @Test
    fun a_positional_darkTheme_argument_still_binds_the_way_it_did() {
        // `darkTheme` stayed the first parameter so this keeps working. It is the reason the signature
        // is not (light, dark, darkTheme, content) as a first sketch had it.
        val colors = colorsUnder { body -> KinetixTheme(true) { body() } }
        assertEquals(DarkKinetixColors, colors)
    }

    // MARK: partial customisation

    @Test
    fun one_role_can_be_changed_by_copying_the_shipped_set() {
        val branded = LightKinetixColors.copy(action = Color(0xffc2410c))
        val colors = colorsUnder { body -> KinetixTheme(darkTheme = false, light = branded) { body() } }

        assertEquals(Color(0xffc2410c), colors.action)
        // Everything else still follows the library.
        assertEquals(LightKinetixColors.background, colors.background)
    }
}
