//
// KinetixMotion.swift — generated by Style Dictionary. Do not edit.
//

public enum KinetixDuration {
    public static let instant = Duration.milliseconds(100)
    public static let fast = Duration.milliseconds(200)
    public static let base = Duration.milliseconds(300)
    public static let slow = Duration.milliseconds(500)
    public static let slower = Duration.milliseconds(1000)
}

/// (x1, y1, x2, y2) cubic-bezier control points.
public enum KinetixEasing {
    public static let linear: (Double, Double, Double, Double) = (0, 0, 1, 1)
    public static let standard: (Double, Double, Double, Double) = (0.4, 0, 0.2, 1)
    public static let enter: (Double, Double, Double, Double) = (0, 0, 0.2, 1)
    public static let exit: (Double, Double, Double, Double) = (0.4, 0, 1, 1)
    public static let emphasized: (Double, Double, Double, Double) = (0.2, 0, 0, 1)
}

public enum KinetixOpacity {
    public static let hidden: Double = 0
    public static let disabled: Double = 0.5
    public static let muted: Double = 0.7
    public static let visible: Double = 1
}

public enum KinetixZIndex {
    public static let base = 0
    public static let raised = 1
    public static let docked = 10
    public static let focus = 20
    public static let sticky = 40
    public static let overlay = 50
}

/// Spatial scale in points — an 8-unit grid with a 4-unit half-step (see /docs/foundations).
public enum KinetixSpacing {
    public static let space0: Double = 0
    public static let space1: Double = 4
    public static let space2: Double = 8
    public static let space3: Double = 12
    public static let space4: Double = 16
    public static let space5: Double = 20
    public static let space6: Double = 24
    public static let space7: Double = 28
    public static let space8: Double = 32
    public static let space10: Double = 40
    public static let space12: Double = 48
    public static let space16: Double = 64
    public static let space20: Double = 80
    public static let space24: Double = 96
    public static let space32: Double = 128
}

public enum KinetixRadius {
    public static let none: Double = 0
    public static let sm: Double = 4
    public static let md: Double = 8
    public static let lg: Double = 12
    public static let xl: Double = 16
    public static let xxl: Double = 24
    public static let full: Double = 9999
}
