//
// KinetixType.swift — generated by Style Dictionary. Do not edit.
//

import SwiftUI

public struct KinetixTextStyle {
  public let font: Font
  public let lineHeight: CGFloat
  public let tracking: CGFloat
}

public enum KinetixType {
    public static let displayLg = KinetixTextStyle(font: .custom("Montserrat", size: 57, relativeTo: .largeTitle).weight(.medium), lineHeight: 64, tracking: -0.25)
    public static let displayMd = KinetixTextStyle(font: .custom("Montserrat", size: 45, relativeTo: .largeTitle).weight(.medium), lineHeight: 52, tracking: 0)
    public static let displaySm = KinetixTextStyle(font: .custom("Montserrat", size: 36, relativeTo: .largeTitle).weight(.regular), lineHeight: 44, tracking: 0)
    public static let headlineLg = KinetixTextStyle(font: .custom("Montserrat", size: 32, relativeTo: .largeTitle).weight(.semibold), lineHeight: 40, tracking: 0)
    public static let headlineMd = KinetixTextStyle(font: .custom("Montserrat", size: 28, relativeTo: .title).weight(.regular), lineHeight: 36, tracking: 0)
    public static let headlineSm = KinetixTextStyle(font: .custom("Montserrat", size: 24, relativeTo: .title2).weight(.regular), lineHeight: 32, tracking: 0)
    public static let titleLg = KinetixTextStyle(font: .custom("Montserrat", size: 22, relativeTo: .title2).weight(.regular), lineHeight: 28, tracking: 0)
    public static let titleMd = KinetixTextStyle(font: .custom("Montserrat", size: 16, relativeTo: .callout).weight(.medium), lineHeight: 24, tracking: 0.15)
    public static let titleSm = KinetixTextStyle(font: .custom("Montserrat", size: 14, relativeTo: .subheadline).weight(.medium), lineHeight: 20, tracking: 0.1)
    public static let titleDialog = KinetixTextStyle(font: .custom("Montserrat", size: 18, relativeTo: .headline).weight(.semibold), lineHeight: 24, tracking: 0)
    public static let labelLg = KinetixTextStyle(font: .custom("Montserrat", size: 14, relativeTo: .subheadline).weight(.medium), lineHeight: 20, tracking: 0.1)
    public static let labelMd = KinetixTextStyle(font: .custom("Montserrat", size: 12, relativeTo: .caption).weight(.medium), lineHeight: 16, tracking: 0.5)
    public static let labelSm = KinetixTextStyle(font: .custom("Montserrat", size: 11, relativeTo: .caption2).weight(.medium), lineHeight: 16, tracking: 0.5)
    public static let bodyLg = KinetixTextStyle(font: .custom("Montserrat", size: 16, relativeTo: .callout).weight(.regular), lineHeight: 24, tracking: 0.5)
    public static let bodyMd = KinetixTextStyle(font: .custom("Montserrat", size: 14, relativeTo: .subheadline).weight(.regular), lineHeight: 20, tracking: 0.25)
    public static let bodySm = KinetixTextStyle(font: .custom("Montserrat", size: 12, relativeTo: .caption).weight(.regular), lineHeight: 16, tracking: 0)
}
