/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Alert, AlertDescription, AlertTitle } from "@kinetixui/ui";
import { Terminal } from "lucide-react";

const Demo = () => (
    <Alert className="max-w-md">
      <Terminal className="size-4" />
      <AlertTitle>Heads up!</AlertTitle>
      <AlertDescription>You can add components to your app using the CLI.</AlertDescription>
    </Alert>
  );

const meta = {
  title: "Feedback/Alert",
  component: Alert,
  args: { variant: "default" },
  argTypes: {
    variant: { control: "inline-radio", options: ["default", "destructive", "success", "warning", "info"] },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Alert>\\n  <Terminal className=\"size-4\" />\\n  <AlertTitle>Heads up!</AlertTitle>\\n  <AlertDescription>You can add components to your app using the CLI.</AlertDescription>\\n</Alert>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <Alert {...args} className="max-w-md">
      <AlertTitle>Heads up!</AlertTitle>
      <AlertDescription>You can add components to your app using the CLI.</AlertDescription>
    </Alert>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
