/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { AppBar, AppBarActions, AppBarBrand, AppBarLink, AppBarNav } from "@kinetixui/ui";
import { Bell } from "lucide-react";

const Demo = () => (
    <AppBar className="w-full max-w-2xl rounded-md border">
      <AppBarBrand>
        <span className="grid size-6 place-items-center rounded bg-primary text-[11px] font-bold text-primary-foreground">
          A
        </span>
        Acme
      </AppBarBrand>
      <AppBarNav>
        <AppBarLink href="#" active>
          Overview
        </AppBarLink>
        <AppBarLink href="#">Reports</AppBarLink>
        <AppBarLink href="#">Team</AppBarLink>
      </AppBarNav>
      <AppBarActions>
        <button
          type="button"
          aria-label="Notifications"
          className="flex size-9 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-foreground"
        >
          <Bell className="size-4" />
        </button>
        <span className="grid size-8 place-items-center rounded-full bg-muted text-xs font-medium">KZ</span>
      </AppBarActions>
    </AppBar>
  );

const meta = {
  title: "Components/AppBar",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<AppBar>\\n  <AppBarBrand>Acme</AppBarBrand>\\n  <AppBarNav>\\n    <AppBarLink href=\"/\" active>Overview</AppBarLink>\\n    <AppBarLink href=\"/reports\">Reports</AppBarLink>\\n    <AppBarLink href=\"/team\">Team</AppBarLink>\\n  </AppBarNav>\\n  <AppBarActions>\\n    <Button variant=\"Ghost\" size=\"icon\"><Bell /></Button>\\n    <Avatar>…</Avatar>\\n  </AppBarActions>\\n</AppBar>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
