/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { AspectRatio } from "@kinetixui/ui";

const Demo = () => (
    <div className="w-[280px]">
      <AspectRatio ratio={16 / 9} className="rounded-md bg-muted" />
    </div>
  );

const meta = {
  title: "Foundations/AspectRatio",
  component: AspectRatio,
  args: { ratio: 1.7778 },
  argTypes: { ratio: { control: { type: "number", step: 0.05 } } },
  parameters: {
    layout: "centered",
    docs: { source: { code: `<AspectRatio ratio={16 / 9} className="bg-muted rounded-md" />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <div className="w-64">
      <AspectRatio {...args} className="rounded-md bg-muted" />
    </div>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
