/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Avatar, AvatarFallback } from "@kinetixui/ui";

const Demo = () => (
    <Avatar>
      <AvatarFallback>KX</AvatarFallback>
    </Avatar>
  );

const meta = {
  title: "Data Display/Avatar",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Avatar>\\n  <AvatarImage src=\"/avatar.png\" alt=\"@kinetixui\" />\\n  <AvatarFallback>KX</AvatarFallback>\\n</Avatar>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
