/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Avatar, AvatarFallback, AvatarGroup } from "@kinetixui/ui";

const Demo = () => (
    <AvatarGroup max={3}>
      <Avatar>
        <AvatarFallback>JD</AvatarFallback>
      </Avatar>
      <Avatar>
        <AvatarFallback>AK</AvatarFallback>
      </Avatar>
      <Avatar>
        <AvatarFallback>MO</AvatarFallback>
      </Avatar>
      <Avatar>
        <AvatarFallback>RS</AvatarFallback>
      </Avatar>
      <Avatar>
        <AvatarFallback>TL</AvatarFallback>
      </Avatar>
    </AvatarGroup>
  );

const meta = {
  title: "Data Display/AvatarGroup",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<AvatarGroup max={3}>\\n  <Avatar><AvatarFallback>JD</AvatarFallback></Avatar>\\n  <Avatar><AvatarFallback>AK</AvatarFallback></Avatar>\\n  <Avatar><AvatarFallback>MO</AvatarFallback></Avatar>\\n</AvatarGroup>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
