/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Badge } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex flex-wrap gap-2">
      <Badge>Default</Badge>
      <Badge variant="secondary">Secondary</Badge>
      <Badge variant="destructive">Destructive</Badge>
      <Badge variant="outline">Outline</Badge>
      <Badge variant="subtle">Subtle</Badge>
    </div>
  );

const meta = {
  title: "Feedback/Badge",
  component: Badge,
  args: { variant: "default", children: "Badge" },
  argTypes: {
    variant: { control: "select", options: ["default", "secondary", "destructive", "outline", "subtle"] },
    children: { control: "text" },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Badge>Default</Badge>\n<Badge variant="secondary">Secondary</Badge>\n<Badge variant="destructive">Destructive</Badge>\n<Badge variant="outline">Outline</Badge>\n<Badge variant="subtle">Subtle</Badge>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <Badge {...args} /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
