/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Banner } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex w-full flex-col gap-3">
      <Banner variant="information" onDismiss={() => {}} action={{ label: "Learn more" }}>
        A new version of KinetixUI is available.
      </Banner>
      <Banner variant="action" action={{ label: "Upgrade" }}>
        You&rsquo;re on the free plan — upgrade for unlimited projects.
      </Banner>
    </div>
  );

const meta = {
  title: "Feedback/Banner",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Banner variant=\"information\" onDismiss={close} action={{ label: \"Learn more\" }}>\\n  A new version of KinetixUI is available.\\n</Banner>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
