/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button, ButtonGroup } from "@kinetixui/ui";
import { Bold, Italic, Underline } from "lucide-react";

const Demo = () => (
    <ButtonGroup>
      <Button variant="Outline" size="icon" aria-label="Bold">
        <Bold />
      </Button>
      <Button variant="Outline" size="icon" aria-label="Italic">
        <Italic />
      </Button>
      <Button variant="Outline" size="icon" aria-label="Underline">
        <Underline />
      </Button>
    </ButtonGroup>
  );

const meta = {
  title: "Controls & Actions/ButtonGroup",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<ButtonGroup>\\n  <Button variant=\"Outline\" size=\"icon\"><Bold /></Button>\\n  <Button variant=\"Outline\" size=\"icon\"><Italic /></Button>\\n  <Button variant=\"Outline\" size=\"icon\"><Underline /></Button>\\n</ButtonGroup>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
