/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Calendar } from "@kinetixui/ui";

const Demo = () => {
    // no initial value: seeding with `new Date()` would bake "today" into the
    // static build's server-rendered HTML, which then mismatches the client's
    // own "today" the moment a day passes without a rebuild.
    const [date, setDate] = React.useState<Date | undefined>();
    return <Calendar mode="single" selected={date} onSelect={setDate} className="rounded-md border" />;
  };

const meta = {
  title: "Form Inputs/Calendar",
  parameters: {
    layout: "padded",
    docs: { source: { code: `const [date, setDate] = React.useState<Date>()\n<Calendar mode="single" selected={date} onSelect={setDate} className="rounded-md border" />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
