/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button, Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, Input, Label, Switch } from "@kinetixui/ui";

const Demo = () => (
    <Card className="w-[320px]">
      <CardHeader>
        <CardTitle>Create project</CardTitle>
        <CardDescription>Deploy your new project in one click.</CardDescription>
      </CardHeader>
      <CardContent>
        <Input placeholder="Project name" />
      </CardContent>
      <CardFooter className="justify-between">
        <Button variant="Outline" size="sm">Cancel</Button>
        <Button size="sm">Deploy</Button>
      </CardFooter>
    </Card>
  );

const meta = {
  title: "Data Display/Card",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Card>\\n  <CardHeader>\\n    <CardTitle>Create project</CardTitle>\\n    <CardDescription>Deploy your new project in one click.</CardDescription>\\n  </CardHeader>\\n  <CardContent>…</CardContent>\\n  <CardFooter>…</CardFooter>\\n</Card>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };

export const Grouped: StoryObj<typeof meta> = { render: () => (
    <section aria-labelledby="card-grouped-heading" className="w-[36rem] max-w-full rounded-xl bg-surface-grouped p-4 sm:p-6">
      <h2 id="card-grouped-heading" className="mb-4 text-title-md text-foreground">Workspace settings</h2>
      <div className="grid gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Notifications</CardTitle>
            <CardDescription>Choose what reaches your inbox.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex items-center justify-between gap-4">
              <Label htmlFor="card-grouped-digest">Weekly digest</Label>
              <Switch id="card-grouped-digest" defaultChecked />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Danger zone</CardTitle>
            <CardDescription>Archiving hides the workspace from every member.</CardDescription>
          </CardHeader>
          <CardFooter>
            <Button variant="Outline" size="sm">Archive workspace</Button>
          </CardFooter>
        </Card>
      </div>
    </section>
  ) };

export const Dense: StoryObj<typeof meta> = { render: () => (
    <div className="grid w-[40rem] max-w-full gap-3 sm:grid-cols-3">
      {[
        ["Revenue", "$45,231", "+12.5% this month"],
        ["Active users", "2,420", "+8.1% this month"],
        ["Churn", "1.2%", "−0.3% this month"],
      ].map(([label, value, change]) => (
        <Card key={label}>
          <CardContent className="flex flex-col gap-1 p-4">
            <span className="text-body-sm text-muted-foreground">{label}</span>
            <span className="text-headline-sm font-medium tabular-nums">{value}</span>
            <span className="text-body-sm text-muted-foreground">{change}</span>
          </CardContent>
        </Card>
      ))}
    </div>
  ) };

export const Interactive: StoryObj<typeof meta> = { render: () => (
    <div className="grid w-[40rem] max-w-full gap-4 sm:grid-cols-2">
      <Card asChild>
        <a href="#reports-q3">
          <CardHeader>
            <CardTitle>Q3 report</CardTitle>
            <CardDescription>Revenue, churn and cohort retention.</CardDescription>
          </CardHeader>
        </a>
      </Card>
      <Card asChild>
        <a href="#reports-q4" aria-current="page">
          <CardHeader>
            <CardTitle>Q4 report</CardTitle>
            <CardDescription>The report you are viewing.</CardDescription>
          </CardHeader>
        </a>
      </Card>
      <Card asChild>
        <button type="button" aria-pressed="true" className="p-6">
          <span className="block font-semibold leading-none tracking-tight">Daily backups</span>
          <span className="mt-1.5 block text-sm text-muted-foreground">Included in this plan.</span>
        </button>
      </Card>
      <Card asChild>
        <button type="button" aria-pressed="false" className="p-6">
          <span className="block font-semibold leading-none tracking-tight">Audit log</span>
          <span className="mt-1.5 block text-sm text-muted-foreground">Add to this plan.</span>
        </button>
      </Card>
    </div>
  ) };
