/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Checkbox, Label } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex items-center gap-2">
      <Checkbox id="c1" defaultChecked />
      <Label htmlFor="c1">Accept terms and conditions</Label>
    </div>
  );

const meta = {
  title: "Form Inputs/Checkbox",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<div className="flex items-center gap-2">\n  <Checkbox id="c1" />\n  <Label htmlFor="c1">Accept terms and conditions</Label>\n</div>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
