/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Card, CardContent, Checkbox, Label, Select } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex items-center gap-2">
      <Checkbox id="c1" defaultChecked />
      <Label htmlFor="c1">Accept terms and conditions</Label>
    </div>
  );

const meta = {
  title: "Form Inputs/Checkbox",
  component: Checkbox,
  args: { disabled: false, defaultChecked: false },
  argTypes: { disabled: { control: "boolean" }, defaultChecked: { control: "boolean" } },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<div className=\"flex items-center gap-2\">\\n  <Checkbox id=\"c1\" />\\n  <Label htmlFor=\"c1\">Accept terms and conditions</Label>\\n</div>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <Checkbox aria-label="Accept terms" {...args} /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };

export const States: StoryObj<typeof meta> = { render: () => (
    <Card className="w-[22rem] max-w-full">
      <CardContent className="grid gap-4 p-6">
        {([
          ["unchecked", "Email me about product updates", {}],
          ["checked", "Email me about security alerts", { defaultChecked: true }],
          ["mixed", "Select all regions", { checked: "indeterminate" }],
          ["invalid", "I accept the terms of service", { "aria-invalid": true, "aria-describedby": "cb-terms-error" }],
          ["invalid-checked", "I accept the data processing terms", { "aria-invalid": true, defaultChecked: true }],
          ["disabled", "Archive automatically (admins only)", { disabled: true }],
          ["disabled-checked", "Keep an audit log (always on)", { disabled: true, defaultChecked: true }],
        ] as const).map(([key, label, props]) => (
          <div key={key} className="flex items-center gap-3">
            <Checkbox id={`cb-${key}`} data-kx-case={key} {...props} />
            <Label htmlFor={`cb-${key}`}>{label}</Label>
          </div>
        ))}
        <p id="cb-terms-error" className="text-body-sm text-destructive">Accept the terms to continue.</p>
      </CardContent>
    </Card>
  ) };
