/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { CircularProgress } from "@kinetixui/ui";

const Demo = () => {
    const [v, setV] = React.useState(25);
    React.useEffect(() => {
      const t = setInterval(() => setV((c) => (c >= 100 ? 25 : c + 5)), 400);
      return () => clearInterval(t);
    }, []);
    return (
      <div className="flex items-center gap-6">
        <CircularProgress value={v} showValue />
        <CircularProgress value={v} size={64} strokeWidth={6} showValue />
        <CircularProgress value={v} />
      </div>
    );
  };

const meta = {
  title: "Feedback/CircularProgress",
  component: CircularProgress,
  args: { value: 66, size: 48, strokeWidth: 4, showValue: true },
  argTypes: {
    value: { control: { type: "range", min: 0, max: 100 } },
    size: { control: { type: "range", min: 24, max: 120 } },
    strokeWidth: { control: { type: "range", min: 2, max: 12 } },
    showValue: { control: "boolean" },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<CircularProgress value={66} showValue />\\n<CircularProgress value={66} size={64} strokeWidth={6} showValue />", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <CircularProgress {...args} /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
