/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { CircularProgress } from "@kinetixui/ui";

const Demo = () => {
    const [v, setV] = React.useState(25);
    React.useEffect(() => {
      const t = setInterval(() => setV((c) => (c >= 100 ? 25 : c + 5)), 400);
      return () => clearInterval(t);
    }, []);
    return (
      <div className="flex items-center gap-6">
        <CircularProgress value={v} showValue />
        <CircularProgress value={v} size={64} strokeWidth={6} showValue />
        <CircularProgress value={v} />
      </div>
    );
  };

const meta = {
  title: "Feedback/CircularProgress",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<CircularProgress value={66} showValue />\n<CircularProgress value={66} size={64} strokeWidth={6} showValue />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
