/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button, CodeBlock } from "@kinetixui/ui";

const Demo = () => (
    <CodeBlock
      className="w-full max-w-lg"
      filename="button.tsx"
      code={`export function Button({ children }) {\n  return <button className="btn">{children}</button>;\n}`}
    />
  );

const meta = {
  title: "Foundations/CodeBlock",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<CodeBlock filename=\"button.tsx\" code={source} />", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
