/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { ColorPicker } from "@kinetixui/ui";

const Demo = () => {
    const [color, setColor] = React.useState("#3b82f6");
    return (
      <ColorPicker
        value={color}
        onChange={setColor}
        swatches={["#ef4444", "#f97316", "#eab308", "#22c55e", "#3b82f6", "#8b5cf6", "#ec4899"]}
      />
    );
  };

const meta = {
  title: "Form Inputs/ColorPicker",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<ColorPicker\\n  value={color}\\n  onChange={setColor}\\n  swatches={[\"#ef4444\", \"#f97316\", \"#eab308\", \"#22c55e\", \"#3b82f6\"]}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
