/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Command as Cmd, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@kinetixui/ui";
import { Search } from "lucide-react";

const Demo = () => (
    <Cmd className="w-[240px] rounded-lg border">
      <CommandInput placeholder="Search framework…" />
      <CommandList>
        <CommandEmpty>No framework found.</CommandEmpty>
        <CommandGroup>
          {["Next.js", "SvelteKit", "Nuxt", "Remix", "Astro"].map((f) => (
            <CommandItem key={f}>{f}</CommandItem>
          ))}
        </CommandGroup>
      </CommandList>
    </Cmd>
  );

const meta = {
  title: "Controls & Actions/Combobox",
  parameters: {
    layout: "centered",
    docs: { source: { code: "// Popover + Command\\n<Popover>\\n  <PopoverTrigger asChild><Button variant=\"Outline\">Select framework…</Button></PopoverTrigger>\\n  <PopoverContent className=\"p-0\">\\n    <Command>…</Command>\\n  </PopoverContent>\\n</Popover>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
