/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Calendar, Command as Cmd, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@kinetixui/ui";
import { Search } from "lucide-react";

const Demo = () => (
    <Cmd className="max-w-[420px] rounded-lg border shadow-md">
      <CommandInput placeholder="Type a command or search…" />
      <CommandList>
        <CommandEmpty>No results found.</CommandEmpty>
        <CommandGroup heading="Suggestions">
          <CommandItem>Calendar</CommandItem>
          <CommandItem>Search Emoji</CommandItem>
          <CommandItem>Launch</CommandItem>
        </CommandGroup>
      </CommandList>
    </Cmd>
  );

const meta = {
  title: "Controls & Actions/Command",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Command>\\n  <CommandInput placeholder=\"Type a command…\" />\\n  <CommandList>\\n    <CommandEmpty>No results found.</CommandEmpty>\\n    <CommandGroup heading=\"Suggestions\">\\n      <CommandItem>Calendar</CommandItem>\\n    </CommandGroup>\\n  </CommandList>\\n</Command>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
