/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { ComparisonSlider } from "@kinetixui/ui";

const Demo = () => (
    <ComparisonSlider
      className="w-full max-w-md"
      beforeLabel="Before"
      afterLabel="After"
      before={<div className="flex size-full items-center justify-center bg-muted text-body-sm text-muted-foreground">Original</div>}
      after={<div className="flex size-full items-center justify-center bg-primary/15 text-body-sm text-primary">Redesign</div>}
    />
  );

const meta = {
  title: "Controls & Actions/ComparisonSlider",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<ComparisonSlider\\n  beforeLabel=\"Before\"\\n  afterLabel=\"After\"\\n  before={<img src=\"/before.jpg\" alt=\"\" />}\\n  after={<img src=\"/after.jpg\" alt=\"\" />}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
