/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { DataTable } from "@kinetixui/ui";

const Demo = () => {
    const columns = [
      { accessorKey: "invoice", header: "Invoice" },
      { accessorKey: "status", header: "Status" },
      { accessorKey: "amount", header: "Amount" },
    ] as never;
    const data = [
      { invoice: "INV001", status: "Paid", amount: "$250.00" },
      { invoice: "INV002", status: "Pending", amount: "$150.00" },
      { invoice: "INV003", status: "Unpaid", amount: "$350.00" },
    ];
    return <DataTable columns={columns} data={data} pageSize={5} />;
  };

const meta = {
  title: "Data Display/DataTable",
  parameters: {
    layout: "padded",
    docs: { source: { code: `const columns: ColumnDef<Invoice>[] = [\n  { accessorKey: "invoice", header: "Invoice" },\n  { accessorKey: "amount", header: "Amount" },\n]\n<DataTable columns={columns} data={data} />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
