/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { DatePicker } from "@kinetixui/ui";

const Demo = () => {
    const [date, setDate] = React.useState<Date | undefined>();
    return (
      <DatePicker
        label="Appointment date"
        value={date}
        onChange={setDate}
        helperText="Choose a weekday"
        className="w-[280px]"
      />
    );
  };

const meta = {
  title: "Form Inputs/DatePicker",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<DatePicker\n  label="Appointment date"\n  value={date}\n  onChange={setDate}\n  helperText="Choose a weekday"\n/>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
