/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Avatar, DescriptionList, DescriptionListItem } from "@kinetixui/ui";

const Demo = () => (
    <DescriptionList className="w-full max-w-sm">
      <DescriptionListItem term="Category">Data Display</DescriptionListItem>
      <DescriptionListItem term="Built on">Radix Avatar</DescriptionListItem>
      <DescriptionListItem term="Platforms">React, SwiftUI, Compose, Flutter</DescriptionListItem>
      <DescriptionListItem term="CLI">npx @kinetixui/cli add avatar</DescriptionListItem>
    </DescriptionList>
  );

const meta = {
  title: "Data Display/DescriptionList",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<DescriptionList>\\n  <DescriptionListItem term=\"Category\">Data Display</DescriptionListItem>\\n  <DescriptionListItem term=\"Built on\">Radix Avatar</DescriptionListItem>\\n</DescriptionList>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
