/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { DiffViewer } from "@kinetixui/ui";

const Demo = () => (
    <DiffViewer
      className="w-full max-w-md"
      mode="split"
      oldText={'{\n  "name": "kinetixui",\n  "version": "0.10.0",\n  "private": true\n}'}
      newText={'{\n  "name": "kinetixui",\n  "version": "0.11.0",\n  "stable": false\n}'}
    />
  );

const meta = {
  title: "Data Display/DiffViewer",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<DiffViewer\\n  mode=\"split\"\\n  oldText={before}\\n  newText={after}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
