/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button, KinetixDirectionProvider, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@kinetixui/ui";

const Demo = () => {
    const [dir, setDir] = React.useState<"ltr" | "rtl">("rtl");
    return (
      <div className="flex w-full max-w-sm flex-col items-center gap-4">
        <div className="flex gap-2">
          {(["ltr", "rtl"] as const).map((d) => (
            <Button key={d} size="sm" variant={dir === d ? "Primary" : "Outline"} onClick={() => setDir(d)}>
              {d.toUpperCase()}
            </Button>
          ))}
        </div>
        {/* `dir` on the element mirrors the layout; the provider is what makes Radix's own portaled
            content agree with it — without it the menu would open left-aligned in an RTL page. */}
        <KinetixDirectionProvider dir={dir}>
          <div dir={dir} className="flex w-full justify-start rounded-md border border-border p-4">
            <Select>
              <SelectTrigger className="w-[220px]" aria-label="Fruit">
                <SelectValue placeholder="Select a fruit" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="apple">Apple</SelectItem>
                <SelectItem value="banana">Banana</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </KinetixDirectionProvider>
      </div>
    );
  };

const meta = {
  title: "Components/DirectionProvider",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<html dir={dir}>\n  <KinetixDirectionProvider dir={dir}>\n    <Select>\n      <SelectTrigger><SelectValue placeholder=\"Select a fruit\" /></SelectTrigger>\n      <SelectContent>\n        <SelectItem value=\"apple\">Apple</SelectItem>\n      </SelectContent>\n    </Select>\n  </KinetixDirectionProvider>\n</html>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
