/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Button, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@kinetixui/ui";

const Demo = () => (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="Outline">Open</Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-44">
        <DropdownMenuLabel>My Account</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem>Profile</DropdownMenuItem>
        <DropdownMenuItem>Billing</DropdownMenuItem>
        <DropdownMenuItem>Team</DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );

const meta = {
  title: "Overlays/DropdownMenu",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<DropdownMenu>\\n  <DropdownMenuTrigger asChild><Button variant=\"Outline\">Open</Button></DropdownMenuTrigger>\\n  <DropdownMenuContent>…</DropdownMenuContent>\\n</DropdownMenu>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
