/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button, Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@kinetixui/ui";
import { Search } from "lucide-react";

const Demo = () => (
    <Empty className="w-full max-w-sm rounded-lg border border-dashed">
      <EmptyHeader>
        <EmptyMedia variant="icon">
          <Search />
        </EmptyMedia>
        <EmptyTitle>No results found</EmptyTitle>
        <EmptyDescription>Try adjusting your search or filters.</EmptyDescription>
      </EmptyHeader>
      <EmptyContent>
        <Button variant="Outline" size="sm">
          Clear filters
        </Button>
      </EmptyContent>
    </Empty>
  );

const meta = {
  title: "Feedback/Empty",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Empty>\\n  <EmptyHeader>\\n    <EmptyMedia variant=\"icon\"><Search /></EmptyMedia>\\n    <EmptyTitle>No results found</EmptyTitle>\\n    <EmptyDescription>Try adjusting your search or filters.</EmptyDescription>\\n  </EmptyHeader>\\n  <EmptyContent>\\n    <Button variant=\"Outline\" size=\"sm\">Clear filters</Button>\\n  </EmptyContent>\\n</Empty>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
