/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Fab } from "@kinetixui/ui";
import { Plus } from "lucide-react";

const Demo = () => (
    <div className="flex items-center gap-4">
      <Fab aria-label="Add">
        <Plus />
      </Fab>
      <Fab extended>
        <Plus />
        New item
      </Fab>
      <Fab variant="Secondary" size="sm" aria-label="Add">
        <Plus />
      </Fab>
    </div>
  );

const meta = {
  title: "Controls & Actions/Fab",
  component: Fab,
  args: { variant: "Primary", size: "default", extended: false },
  argTypes: {
    variant: { control: "inline-radio", options: ["Primary", "Secondary"] },
    size: { control: "inline-radio", options: ["default", "sm"] },
    extended: { control: "boolean" },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Fab aria-label=\"Add\">\\n  <Plus />\\n</Fab>\\n\\n<Fab extended>\\n  <Plus />\\n  New item\\n</Fab>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <Fab {...args} aria-label="Add">
      <Plus />
      {args.extended ? "New item" : null}
    </Fab>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
