/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Fab } from "@kinetixui/ui";
import { Plus } from "lucide-react";

const Demo = () => (
    <div className="flex items-center gap-4">
      <Fab aria-label="Add">
        <Plus />
      </Fab>
      <Fab extended>
        <Plus />
        New item
      </Fab>
      <Fab variant="Secondary" size="sm" aria-label="Add">
        <Plus />
      </Fab>
    </div>
  );

const meta = {
  title: "Controls & Actions/Fab",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Fab aria-label="Add">\n  <Plus />\n</Fab>\n\n<Fab extended>\n  <Plus />\n  New item\n</Fab>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
