/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Field, FieldControl, FieldDescription, FieldLabel, FieldMessage, Input } from "@kinetixui/ui";

const Demo = () => {
    const [v, setV] = React.useState("");
    const invalid = v.length > 0 && !v.includes("@");
    return (
      <div className="w-full max-w-sm">
        <Field invalid={invalid}>
          <FieldLabel>Email</FieldLabel>
          <FieldControl>
            <Input value={v} onChange={(e) => setV(e.target.value)} placeholder="you@example.com" />
          </FieldControl>
          <FieldDescription>We&rsquo;ll only use it to send receipts.</FieldDescription>
          {invalid && <FieldMessage intent="error">Enter a valid email address.</FieldMessage>}
          {!invalid && v.includes("@") && <FieldMessage intent="success">Looks good.</FieldMessage>}
        </Field>
      </div>
    );
  };

const meta = {
  title: "Form Inputs/Field",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Field invalid={!!error}>\n  <FieldLabel>Email</FieldLabel>\n  <FieldControl><Input type="email" {...register("email")} /></FieldControl>\n  <FieldDescription>We'll only use it to send receipts.</FieldDescription>\n  {error && <FieldMessage intent="error">{error.message}</FieldMessage>}\n</Field>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
