/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { FileUpload } from "@kinetixui/ui";

const Demo = () => {
    const [files, setFiles] = React.useState([
      { id: "1", name: "passport-scan.pdf", size: 245_000, status: "uploaded" as const },
      { id: "2", name: "photo.png", size: 1_200_000, status: "error" as const, error: "File exceeds 1 MB limit" },
    ]);
    return (
      <FileUpload
        className="w-full max-w-sm"
        multiple
        helperText="PDF, PNG up to 5 MB"
        files={files}
        onFilesSelected={(picked) =>
          setFiles((f) => [...f, ...picked.map((p, i) => ({ id: `new-${i}-${p.name}`, name: p.name, size: p.size, status: "uploaded" as const }))])
        }
        onRemove={(id) => setFiles((f) => f.filter((x) => x.id !== id))}
      />
    );
  };

const meta = {
  title: "Form Inputs/FileUpload",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<FileUpload\\n  multiple\\n  files={files}\\n  onFilesSelected={(picked) => upload(picked)}\\n  onRemove={(id) => removeFile(id)}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
