/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Footer, FooterBottom, FooterColumn, FooterLink } from "@kinetixui/ui";

const Demo = () => (
    <Footer className="w-full max-w-lg rounded-md">
      <div className="grid grid-cols-2 gap-6">
        <FooterColumn title="Product">
          <FooterLink href="#">Overview</FooterLink>
          <FooterLink href="#">Pricing</FooterLink>
        </FooterColumn>
        <FooterColumn title="Company">
          <FooterLink href="#">About</FooterLink>
          <FooterLink href="#">Careers</FooterLink>
        </FooterColumn>
      </div>
      <FooterBottom>
        <span>© 2026 Acme Inc.</span>
        <div className="flex gap-3">
          <FooterLink href="#">Privacy</FooterLink>
          <FooterLink href="#">Terms</FooterLink>
        </div>
      </FooterBottom>
    </Footer>
  );

const meta = {
  title: "Data Display/Footer",
  parameters: {
    layout: "padded",
    docs: { source: { code: `<Footer>\n  <div className="grid grid-cols-2 gap-6">\n    <FooterColumn title="Product">\n      <FooterLink href="/pricing">Pricing</FooterLink>\n    </FooterColumn>\n  </div>\n  <FooterBottom>© 2026 Acme Inc.</FooterBottom>\n</Footer>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
