/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Button, HoverCard, HoverCardContent, HoverCardTrigger } from "@kinetixui/ui";

const Demo = () => (
    <HoverCard>
      <HoverCardTrigger asChild>
        <Button variant="Link">@kinetixui</Button>
      </HoverCardTrigger>
      <HoverCardContent>One token architecture, in motion across every platform.</HoverCardContent>
    </HoverCard>
  );

const meta = {
  title: "Overlays/HoverCard",
  component: HoverCard,
  args: { openDelay: 200, closeDelay: 200 },
  argTypes: {
    openDelay: { control: { type: "number", step: 100 } },
    closeDelay: { control: { type: "number", step: 100 } },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<HoverCard>\\n  <HoverCardTrigger>@kinetixui</HoverCardTrigger>\\n  <HoverCardContent>…</HoverCardContent>\\n</HoverCard>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <HoverCard {...args}>
      <HoverCardTrigger asChild>
        <Button variant="Link">@kinetixui</Button>
      </HoverCardTrigger>
      <HoverCardContent>One token architecture, in motion across every platform.</HoverCardContent>
    </HoverCard>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
