/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Image } from "@kinetixui/ui";

const Demo = () => (
    <div className="grid w-full max-w-md grid-cols-3 gap-3">
      <Image ratio="1:1" src="https://picsum.photos/seed/kx1/400" alt="" />
      <Image ratio="4:3" src="https://picsum.photos/seed/kx2/400/300" alt="" />
      <Image ratio="3:4" src="https://picsum.photos/seed/kx3/300/400" alt="" />
    </div>
  );

const meta = {
  title: "Foundations/Image",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Image ratio="1:1" src="/photo.jpg" alt="" />\n<Image ratio="4:3" src="/photo.jpg" alt="" />\n<Image ratio="16:9" src="/photo.jpg" alt="" rounded={false} />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
