/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Image } from "@kinetixui/ui";

const Demo = () => (
    <div className="grid w-full max-w-md grid-cols-3 gap-3">
      <Image ratio="1:1" src="https://picsum.photos/seed/kx1/400" alt="" />
      <Image ratio="4:3" src="https://picsum.photos/seed/kx2/400/300" alt="" />
      <Image ratio="3:4" src="https://picsum.photos/seed/kx3/300/400" alt="" />
    </div>
  );

const meta = {
  title: "Foundations/Image",
  component: Image,
  args: { ratio: "4:3", rounded: true },
  argTypes: {
    ratio: { control: "inline-radio", options: ["1:1", "4:3", "3:4", "16:9"] },
    rounded: { control: "boolean" },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Image ratio="1:1" src="/photo.jpg" alt="" />\n<Image ratio="4:3" src="/photo.jpg" alt="" />\n<Image ratio="16:9" src="/photo.jpg" alt="" rounded={false} />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <Image {...args} src="https://picsum.photos/seed/kx/400/300" alt="" className="w-56" />
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
