/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Inform } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex w-full max-w-md flex-col gap-3">
      <Inform variant="information" onDismiss={() => {}}>
        A new software update is available.
      </Inform>
      <Inform variant="success">Your changes have been saved.</Inform>
      <Inform variant="warning">Your subscription expires in 3 days.</Inform>
      <Inform variant="error" action={{ label: "Retry" }}>
        We couldn&rsquo;t process your payment.
      </Inform>
    </div>
  );

const meta = {
  title: "Feedback/Inform",
  component: Inform,
  args: { variant: "information" },
  argTypes: {
    variant: { control: "inline-radio", options: ["information", "warning", "success", "error"] },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Inform variant=\"information\" onDismiss={close}>\\n  A new software update is available.\\n</Inform>\\n\\n<Inform variant=\"error\" action={{ label: \"Retry\", onClick: retry }}>\\n  We couldn't process your payment.\\n</Inform>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <Inform {...args} className="max-w-md">A new software update is available.</Inform>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
