/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput, InputGroupText } from "@kinetixui/ui";
import { Search } from "lucide-react";

const Demo = () => (
    <div className="flex w-full max-w-sm flex-col gap-3">
      <InputGroup>
        <InputGroupText>https://</InputGroupText>
        <InputGroupInput placeholder="kinetixui.com" />
      </InputGroup>
      <InputGroup>
        <InputGroupAddon align="start">$</InputGroupAddon>
        <InputGroupInput placeholder="0.00" inputMode="decimal" />
        <InputGroupText>USD</InputGroupText>
      </InputGroup>
      <InputGroup>
        <InputGroupInput placeholder="Search components…" />
        <InputGroupButton>Search</InputGroupButton>
      </InputGroup>
    </div>
  );

const meta = {
  title: "Form Inputs/InputGroup",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<InputGroup>\\n  <InputGroupText>https://</InputGroupText>\\n  <InputGroupInput placeholder=\"kinetixui.com\" />\\n</InputGroup>\\n\\n<InputGroup>\\n  <InputGroupAddon align=\"start\">$</InputGroupAddon>\\n  <InputGroupInput placeholder=\"0.00\" />\\n  <InputGroupText>USD</InputGroupText>\\n</InputGroup>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
