/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { JsonViewer } from "@kinetixui/ui";

const Demo = () => (
    <JsonViewer
      className="w-full max-w-md"
      data={{
        name: "kinetixui",
        version: "0.11.0",
        platforms: ["react", "swiftui", "compose", "flutter"],
        stable: false,
        tokens: { spacing: 8, radius: { sm: 4, md: 8 } },
        deprecated: null,
      }}
    />
  );

const meta = {
  title: "Data Display/JsonViewer",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<JsonViewer\\n  data={{\\n    name: \"kinetixui\",\\n    version: \"0.11.0\",\\n    platforms: [\"react\", \"swiftui\", \"compose\", \"flutter\"],\\n    stable: false,\\n  }}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
