/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { ColorPicker, DiffViewer, JsonViewer, KanbanBoard, Progress } from "@kinetixui/ui";

const Demo = () => {
    const [columns, setColumns] = React.useState<KanbanColumn[]>([
      {
        id: "todo",
        title: "To Do",
        cards: [
          { id: "1", content: "Design the onboarding flow" },
          { id: "2", content: "Write API docs for /r/registry.json" },
        ],
      },
      {
        id: "in-progress",
        title: "In Progress",
        cards: [{ id: "3", content: "Port ColorPicker to Compose" }],
      },
      {
        id: "done",
        title: "Done",
        cards: [
          { id: "4", content: "Ship DiffViewer" },
          { id: "5", content: "Ship JsonViewer" },
        ],
      },
    ]);
    return <KanbanBoard columns={columns} onColumnsChange={setColumns} className="w-full" />;
  };

const meta = {
  title: "Data Display/KanbanBoard",
  parameters: {
    layout: "padded",
    docs: { source: { code: "<KanbanBoard\\n  columns={columns}\\n  onColumnsChange={setColumns}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
