/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Kbd, KbdGroup } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex items-center gap-4">
      <Kbd>⏎</Kbd>
      <KbdGroup>
        <Kbd>⌘</Kbd>
        <Kbd>K</Kbd>
      </KbdGroup>
    </div>
  );

const meta = {
  title: "Foundations/Kbd",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Kbd>⏎</Kbd>\\n<KbdGroup>\\n  <Kbd>⌘</Kbd>\\n  <Kbd>K</Kbd>\\n</KbdGroup>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
