/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Checkbox, Label } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex items-center gap-2">
      <Checkbox id="terms" />
      <Label htmlFor="terms">Accept terms and conditions</Label>
    </div>
  );

const meta = {
  title: "Foundations/Label",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Label htmlFor="email">Your email address</Label>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
