/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { MarkdownEditor } from "@kinetixui/ui";
import { Bold } from "lucide-react";

const Demo = () => {
    const [text, setText] = React.useState(
      "## Release notes\n\nShipped **MarkdownEditor** — a toolbar over a plain textarea, not `contenteditable`.\n\n- Bold, italic, links\n- Bulleted and numbered lists\n- An optional preview pane",
    );
    return <MarkdownEditor className="w-full" value={text} onChange={setText} rows={8} />;
  };

const meta = {
  title: "Form Inputs/MarkdownEditor",
  parameters: {
    layout: "padded",
    docs: { source: { code: "<MarkdownEditor\\n  value={text}\\n  onChange={setText}\\n  rows={8}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
