/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Marquee } from "@kinetixui/ui";

const Demo = () => (
    <Marquee durationSeconds={18} className="w-full max-w-md">
      {["React", "SwiftUI", "Jetpack Compose", "Flutter"].map((p) => (
        <span key={p} className="flex items-center gap-2 px-4 text-body-sm text-muted-foreground">
          <span className="size-1.5 rounded-full bg-primary" />
          {p}
        </span>
      ))}
    </Marquee>
  );

const meta = {
  title: "Data Display/Marquee",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Marquee durationSeconds={18}>\\n  {items.map((item) => (\\n    <span key={item}>{item}</span>\\n  ))}\\n</Marquee>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
