/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { MessageBubble, TypingIndicator } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex w-full max-w-sm flex-col gap-1.5">
      <MessageBubble variant="received" timestamp="10:42 AM">
        Hey, are we still on for tomorrow?
      </MessageBubble>
      <MessageBubble variant="sent" timestamp="10:43 AM" status="read">
        Yep! See you at 3.
      </MessageBubble>
      <MessageBubble variant="sent" grouped status="delivered">
        I&rsquo;ll bring the slides.
      </MessageBubble>
      <TypingIndicator className="mt-1" />
    </div>
  );

const meta = {
  title: "Data Display/MessageBubble",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<MessageBubble variant=\"received\" timestamp=\"10:42 AM\">\\n  Hey, are we still on for tomorrow?\\n</MessageBubble>\\n<MessageBubble variant=\"sent\" timestamp=\"10:43 AM\" status=\"read\">\\n  Yep! See you at 3.\\n</MessageBubble>\\n<TypingIndicator />", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
