/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Metric } from "@kinetixui/ui";

const Demo = () => (
    <div className="grid w-full max-w-lg grid-cols-2 gap-4">
      <Metric label="Active users" value="2,420" trend="up" change="12%" />
      <Metric label="Churn rate" value="1.2%" trend="down" change="0.3%" />
    </div>
  );

const meta = {
  title: "Feedback/Metric",
  component: Metric,
  args: { label: "Active users", value: "2,420", trend: "up", change: "12%" },
  argTypes: {
    trend: { control: "inline-radio", options: ["up", "down", "neutral"] },
    label: { control: "text" }, value: { control: "text" }, change: { control: "text" },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Metric label="Active users" value="2,420" trend="up" change="12%" />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <Metric {...args} /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
