/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Button, Dialog, Modal } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex flex-wrap gap-3">
      {(["Info", "Confirmation", "Warning", "Destructive"] as const).map((type) => (
        <Modal
          key={type}
          type={type}
          title={`${type} dialog`}
          description="Dialog description text — this modal is the design-source composition (header · divider · body · divider · footer)."
          trigger={<Button variant="Outline">{type}</Button>}
        />
      ))}
    </div>
  );

const meta = {
  title: "Overlays/Modal",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Modal\\n  type=\"Confirmation\"\\n  title=\"Are you sure?\"\\n  description=\"This action cannot be undone.\"\\n  trigger={<Button variant=\"Outline\">Delete</Button>}\\n  onAction={handleDelete}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
