/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { MultiSelect, Select } from "@kinetixui/ui";

const Demo = () => {
    const [value, setValue] = React.useState(["react", "swiftui"]);
    return (
      <MultiSelect
        className="w-full max-w-sm"
        value={value}
        onValueChange={setValue}
        placeholder="Select platforms…"
        options={[
          { value: "react", label: "React" },
          { value: "swiftui", label: "SwiftUI" },
          { value: "compose", label: "Jetpack Compose" },
          { value: "flutter", label: "Flutter" },
        ]}
      />
    );
  };

const meta = {
  title: "Form Inputs/MultiSelect",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<MultiSelect\\n  value={value}\\n  onValueChange={setValue}\\n  placeholder=\"Select platforms…\"\\n  options={[\\n    { value: \"react\", label: \"React\" },\\n    { value: \"swiftui\", label: \"SwiftUI\" },\\n  ]}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
