/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Card, CardContent, Label, NativeSelect, NativeSelectOptGroup, NativeSelectOption, Select } from "@kinetixui/ui";

const Demo = () => (
    <NativeSelect aria-label="Fruit" className="max-w-xs" defaultValue="">
      <NativeSelectOption value="" disabled>
        Select a fruit…
      </NativeSelectOption>
      <NativeSelectOptGroup label="Citrus">
        <NativeSelectOption value="orange">Orange</NativeSelectOption>
        <NativeSelectOption value="lemon">Lemon</NativeSelectOption>
      </NativeSelectOptGroup>
      <NativeSelectOptGroup label="Stone fruit">
        <NativeSelectOption value="peach">Peach</NativeSelectOption>
        <NativeSelectOption value="plum">Plum</NativeSelectOption>
      </NativeSelectOptGroup>
    </NativeSelect>
  );

const meta = {
  title: "Form Inputs/NativeSelect",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<NativeSelect defaultValue=\"\">\\n  <NativeSelectOption value=\"\" disabled>Select a fruit…</NativeSelectOption>\\n  <NativeSelectOptGroup label=\"Citrus\">\\n    <NativeSelectOption value=\"orange\">Orange</NativeSelectOption>\\n  </NativeSelectOptGroup>\\n</NativeSelect>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };

export const EntryStates: StoryObj<typeof meta> = { render: () => (
    <Card className="w-[22rem] max-w-full">
      <CardContent className="grid gap-5 p-6">
        {([
          ["rest", "Country", { defaultValue: "" }],
          ["filled", "Time zone", { defaultValue: "utc" }],
          ["invalid", "Plan", { defaultValue: "", "aria-invalid": true, "aria-describedby": "nsel-invalid-error" }],
          ["disabled", "Data region (locked)", { defaultValue: "utc", disabled: true }],
        ] as const).map(([key, label, props]) => (
          <div key={key} className="grid gap-2">
            <Label htmlFor={`nsel-${key}`}>{label}</Label>
            <NativeSelect id={`nsel-${key}`} data-kx-case={key} {...props}>
              <NativeSelectOption value="" disabled>Choose one</NativeSelectOption>
              <NativeSelectOption value="utc">UTC</NativeSelectOption>
              <NativeSelectOption value="cet">Central European Time</NativeSelectOption>
            </NativeSelect>
            {key === "invalid" ? <p id="nsel-invalid-error" className="text-body-sm text-destructive">Choose a plan to continue.</p> : null}
          </div>
        ))}
      </CardContent>
    </Card>
  ) };
