/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { NativeSelect, NativeSelectOptGroup, NativeSelectOption, Select } from "@kinetixui/ui";

const Demo = () => (
    <NativeSelect className="max-w-xs" defaultValue="">
      <NativeSelectOption value="" disabled>
        Select a fruit…
      </NativeSelectOption>
      <NativeSelectOptGroup label="Citrus">
        <NativeSelectOption value="orange">Orange</NativeSelectOption>
        <NativeSelectOption value="lemon">Lemon</NativeSelectOption>
      </NativeSelectOptGroup>
      <NativeSelectOptGroup label="Stone fruit">
        <NativeSelectOption value="peach">Peach</NativeSelectOption>
        <NativeSelectOption value="plum">Plum</NativeSelectOption>
      </NativeSelectOptGroup>
    </NativeSelect>
  );

const meta = {
  title: "Form Inputs/NativeSelect",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<NativeSelect defaultValue=\"\">\\n  <NativeSelectOption value=\"\" disabled>Select a fruit…</NativeSelectOption>\\n  <NativeSelectOptGroup label=\"Citrus\">\\n    <NativeSelectOption value=\"orange\">Orange</NativeSelectOption>\\n  </NativeSelectOptGroup>\\n</NativeSelect>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
