/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { NavigationBar } from "@kinetixui/ui";
import { Search } from "lucide-react";

const Demo = () => (
    <NavigationBar
      className="w-full max-w-md rounded-md"
      title="Appointments"
      infoText="3 upcoming"
      onBack={() => {}}
      actions={
        <button type="button" aria-label="Search" className="flex size-9 items-center justify-center rounded-full hover:bg-accent">
          <Search className="size-5" />
        </button>
      }
    />
  );

const meta = {
  title: "Navigation/NavigationBar",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<NavigationBar\\n  title=\"Appointments\"\\n  infoText=\"3 upcoming\"\\n  onBack={() => router.back()}\\n  actions={<Button variant=\"Ghost\" size=\"icon\"><Search /></Button>}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
