/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { NotificationCenter, NotificationCenterContent, NotificationCenterTrigger, NotificationItem, PageHeader } from "@kinetixui/ui";

const Demo = () => {
    const [unread, setUnread] = React.useState(2);
    return (
      <NotificationCenter>
        <NotificationCenterTrigger unreadCount={unread} />
        <NotificationCenterContent onMarkAllRead={() => setUnread(0)}>
          <NotificationItem
            unread={unread > 0}
            title="PR #106 merged"
            description="feat(ui): add PageHeader"
            time="2m ago"
          />
          <NotificationItem
            unread={unread > 1}
            title="Deploy succeeded"
            description="v0.11.0 is live"
            time="1h ago"
          />
          <NotificationItem title="Welcome to KinetixUI" time="2d ago" />
        </NotificationCenterContent>
      </NotificationCenter>
    );
  };

const meta = {
  title: "Overlays/NotificationCenter",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<NotificationCenter>\\n  <NotificationCenterTrigger unreadCount={2} />\\n  <NotificationCenterContent onMarkAllRead={markAllRead}>\\n    <NotificationItem unread title=\"PR #106 merged\" time=\"2m ago\" />\\n    <NotificationItem title=\"Welcome to KinetixUI\" time=\"2d ago\" />\\n  </NotificationCenterContent>\\n</NotificationCenter>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
