/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { NumberInput } from "@kinetixui/ui";

const Demo = () => {
    const [v, setV] = React.useState(2);
    return <NumberInput value={v} onChange={setV} min={0} max={10} className="w-32" />;
  };

const meta = {
  title: "Form Inputs/NumberInput",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<NumberInput value={qty} onChange={setQty} min={0} max={10} />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
