/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { NumberInput } from "@kinetixui/ui";

const Demo = () => {
    const [v, setV] = React.useState(2);
    return <NumberInput value={v} onChange={setV} min={0} max={10} className="w-32" />;
  };

const meta = {
  title: "Form Inputs/NumberInput",
  component: NumberInput,
  args: { defaultValue: 2, min: 0, max: 10, step: 1 },
  argTypes: {
    min: { control: "number" }, max: { control: "number" }, step: { control: "number" },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<NumberInput value={qty} onChange={setQty} min={0} max={10} />", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <NumberInput {...args} className="w-32" /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
