/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator, Button, PageHeader } from "@kinetixui/ui";
import { Settings } from "lucide-react";

const Demo = () => (
    <PageHeader
      className="w-full"
      breadcrumb={
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href="#">Projects</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>KinetixUI</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
      }
      title="KinetixUI"
      description="One token architecture, in motion across every platform."
      actions={
        <>
          <Button variant="Outline" size="sm">
            Settings
          </Button>
          <Button size="sm">Deploy</Button>
        </>
      }
    />
  );

const meta = {
  title: "Navigation/PageHeader",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<PageHeader\\n  breadcrumb={<Breadcrumb>...</Breadcrumb>}\\n  title=\"KinetixUI\"\\n  description=\"One token architecture, in motion across every platform.\"\\n  actions={<><Button variant=\"Outline\" size=\"sm\">Settings</Button><Button size=\"sm\">Deploy</Button></>}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
