/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { PasswordInput } from "@kinetixui/ui";

const Demo = () => (
    <div className="w-full max-w-sm">
      <PasswordInput placeholder="••••••••" defaultValue="hunter2" />
    </div>
  );

const meta = {
  title: "Form Inputs/PasswordInput",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<PasswordInput placeholder="••••••••" />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
