/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Progress } from "@kinetixui/ui";

const Demo = () => {
    const [v, setV] = React.useState(13);
    React.useEffect(() => {
      const t = setTimeout(() => setV(66), 600);
      return () => clearTimeout(t);
    }, []);
    return <Progress value={v} className="w-[60%]" />;
  };

const meta = {
  title: "Feedback/Progress",
  component: Progress,
  args: { value: 66 },
  argTypes: { value: { control: { type: "range", min: 0, max: 100 } } },
  parameters: {
    layout: "centered",
    docs: { source: { code: "const [value, setValue] = React.useState(13)\\n// ...\\n<Progress value={value} />", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <Progress {...args} className="w-60" /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
