/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Progress } from "@kinetixui/ui";

const Demo = () => {
    const [v, setV] = React.useState(13);
    React.useEffect(() => {
      const t = setTimeout(() => setV(66), 600);
      return () => clearTimeout(t);
    }, []);
    return <Progress value={v} className="w-[60%]" />;
  };

const meta = {
  title: "Feedback/Progress",
  parameters: {
    layout: "centered",
    docs: { source: { code: `const [value, setValue] = React.useState(13)\n// ...\n<Progress value={value} />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
