/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Avatar, AvatarFallback, Quote } from "@kinetixui/ui";

const Demo = () => (
    <Quote
      className="max-w-md"
      author="Amira K."
      authorTitle="Product Designer"
      avatar={
        <Avatar>
          <AvatarFallback>AK</AvatarFallback>
        </Avatar>
      }
    >
      This is exactly the token workflow our team needed.
    </Quote>
  );

const meta = {
  title: "Data Display/Quote",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Quote author="Amira K." authorTitle="Product Designer" avatar={<Avatar>...</Avatar>}>\n  This is exactly the token workflow our team needed.\n</Quote>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
