/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Label, RadioGroup, RadioGroupItem } from "@kinetixui/ui";

const Demo = () => (
    <RadioGroup defaultValue="comfortable">
      {["default", "comfortable", "compact"].map((v) => (
        <div key={v} className="flex items-center gap-2">
          <RadioGroupItem value={v} id={v} />
          <Label htmlFor={v} className="capitalize">{v}</Label>
        </div>
      ))}
    </RadioGroup>
  );

const meta = {
  title: "Form Inputs/RadioGroup",
  component: RadioGroup,
  args: { defaultValue: "comfortable", disabled: false },
  argTypes: {
    defaultValue: { control: "inline-radio", options: ["default", "comfortable", "compact"] },
    disabled: { control: "boolean" },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<RadioGroup defaultValue=\"comfortable\">\\n  <div className=\"flex items-center gap-2\">\\n    <RadioGroupItem value=\"default\" id=\"r1\" />\\n    <Label htmlFor=\"r1\">Default</Label>\\n  </div>\\n</RadioGroup>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <RadioGroup {...args}>
      {["default", "comfortable", "compact"].map((v) => (
        <div key={v} className="flex items-center gap-2">
          <RadioGroupItem value={v} id={v} />
          <Label htmlFor={v} className="capitalize">{v}</Label>
        </div>
      ))}
    </RadioGroup>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
