/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Rating } from "@kinetixui/ui";

const Demo = () => {
    const [v, setV] = React.useState(3);
    return (
      <div className="flex flex-col gap-3">
        <Rating value={v} onChange={setV} />
        <Rating value={4} readOnly size="sm" />
      </div>
    );
  };

const meta = {
  title: "Form Inputs/Rating",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Rating value={value} onChange={setValue} />\n<Rating value={4} readOnly size="sm" />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
