/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { ScrollArea, Tag } from "@kinetixui/ui";

const Demo = () => (
    <ScrollArea className="h-40 w-56 rounded-md border p-4 text-sm">
      {Array.from({ length: 20 }).map((_, i) => (
        <div key={i} className="py-1">Tag {i + 1}</div>
      ))}
    </ScrollArea>
  );

const meta = {
  title: "Data Display/ScrollArea",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<ScrollArea className="h-40 w-56 rounded-md border p-4">\n  {tags.map((t) => <div key={t}>{t}</div>)}\n</ScrollArea>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
