/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { List, SegmentedControl, SegmentedControlItem } from "@kinetixui/ui";

const Demo = () => (
    <SegmentedControl defaultValue="grid" className="w-full max-w-xs">
      <SegmentedControlItem value="list">List</SegmentedControlItem>
      <SegmentedControlItem value="grid">Grid</SegmentedControlItem>
      <SegmentedControlItem value="board">Board</SegmentedControlItem>
    </SegmentedControl>
  );

const meta = {
  title: "Controls & Actions/SegmentedControl",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<SegmentedControl defaultValue=\"grid\">\\n  <SegmentedControlItem value=\"list\">List</SegmentedControlItem>\\n  <SegmentedControlItem value=\"grid\">Grid</SegmentedControlItem>\\n  <SegmentedControlItem value=\"board\">Board</SegmentedControlItem>\\n</SegmentedControl>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
