/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Card, CardContent, Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@kinetixui/ui";

const Demo = () => (
    <Select>
      <SelectTrigger className="w-[220px]" aria-label="Fruit">
        <SelectValue placeholder="Select a fruit" />
      </SelectTrigger>
      <SelectContent>
        <SelectItem value="apple">Apple</SelectItem>
        <SelectItem value="banana">Banana</SelectItem>
        <SelectItem value="blueberry">Blueberry</SelectItem>
      </SelectContent>
    </Select>
  );

const meta = {
  title: "Form Inputs/Select",
  component: Select,
  args: { disabled: false },
  argTypes: { disabled: { control: "boolean" } },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Select>\\n  <SelectTrigger><SelectValue placeholder=\"Select a fruit\" /></SelectTrigger>\\n  <SelectContent>\\n    <SelectItem value=\"apple\">Apple</SelectItem>\\n  </SelectContent>\\n</Select>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <Select {...args}>
      <SelectTrigger className="w-[220px]" aria-label="Fruit">
        <SelectValue placeholder="Select a fruit" />
      </SelectTrigger>
      <SelectContent>
        <SelectItem value="apple">Apple</SelectItem>
        <SelectItem value="banana">Banana</SelectItem>
        <SelectItem value="blueberry">Blueberry</SelectItem>
      </SelectContent>
    </Select>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };

export const EntryStates: StoryObj<typeof meta> = { render: () => (
    <Card className="w-[22rem] max-w-full">
      <CardContent className="grid gap-5 p-6">
        {([
          ["rest", "Country", {}, {}],
          ["filled", "Time zone", { defaultValue: "utc" }, {}],
          ["invalid", "Plan", {}, { "aria-invalid": true, "aria-describedby": "sel-invalid-error" }],
          ["disabled", "Data region (locked)", { defaultValue: "utc", disabled: true }, {}],
        ] as const).map(([key, label, root, trigger]) => (
          <div key={key} className="grid gap-2">
            <Label htmlFor={`sel-${key}`}>{label}</Label>
            <Select {...root}>
              <SelectTrigger id={`sel-${key}`} data-kx-case={key} {...trigger}>
                <SelectValue placeholder="Choose one" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="utc">UTC</SelectItem>
                <SelectItem value="cet">Central European Time</SelectItem>
              </SelectContent>
            </Select>
            {key === "invalid" ? <p id="sel-invalid-error" className="text-body-sm text-destructive">Choose a plan to continue.</p> : null}
          </div>
        ))}
      </CardContent>
    </Card>
  ) };
