/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@kinetixui/ui";

const Demo = () => (
    <Select>
      <SelectTrigger className="w-[220px]">
        <SelectValue placeholder="Select a fruit" />
      </SelectTrigger>
      <SelectContent>
        <SelectItem value="apple">Apple</SelectItem>
        <SelectItem value="banana">Banana</SelectItem>
        <SelectItem value="blueberry">Blueberry</SelectItem>
      </SelectContent>
    </Select>
  );

const meta = {
  title: "Form Inputs/Select",
  component: Select,
  args: { disabled: false },
  argTypes: { disabled: { control: "boolean" } },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Select>\\n  <SelectTrigger><SelectValue placeholder=\"Select a fruit\" /></SelectTrigger>\\n  <SelectContent>\\n    <SelectItem value=\"apple\">Apple</SelectItem>\\n  </SelectContent>\\n</Select>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <Select {...args}>
      <SelectTrigger className="w-[220px]">
        <SelectValue placeholder="Select a fruit" />
      </SelectTrigger>
      <SelectContent>
        <SelectItem value="apple">Apple</SelectItem>
        <SelectItem value="banana">Banana</SelectItem>
        <SelectItem value="blueberry">Blueberry</SelectItem>
      </SelectContent>
    </Select>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
