/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Separator } from "@kinetixui/ui";

const Demo = () => (
    <div className="text-sm">
      <div className="font-medium">KinetixUI</div>
      <div className="text-muted-foreground">One token architecture.</div>
      <Separator className="my-3" />
      <div className="flex h-5 items-center gap-3">
        <span>Docs</span>
        <Separator orientation="vertical" />
        <span>Components</span>
        <Separator orientation="vertical" />
        <span>Themes</span>
      </div>
    </div>
  );

const meta = {
  title: "Foundations/Separator",
  component: Separator,
  args: { orientation: "horizontal" },
  argTypes: { orientation: { control: "inline-radio", options: ["horizontal", "vertical"] } },
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Separator />\n<Separator orientation="vertical" />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <div className="flex h-16 w-48 items-center justify-center">
      <Separator {...args} />
    </div>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
