/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button, Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@kinetixui/ui";

const Demo = () => (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="Outline">Open</Button>
      </SheetTrigger>
      <SheetContent>
        <SheetHeader>
          <SheetTitle>Edit profile</SheetTitle>
          <SheetDescription>Make changes to your profile here.</SheetDescription>
        </SheetHeader>
      </SheetContent>
    </Sheet>
  );

const meta = {
  title: "Overlays/Sheet",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Sheet>\\n  <SheetTrigger asChild><Button variant=\"Outline\">Open</Button></SheetTrigger>\\n  <SheetContent side=\"right\">…</SheetContent>\\n</Sheet>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
