/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";


const Demo = () => (
    <div className="w-full rounded-lg border p-4 text-sm text-muted-foreground">
      The <code className="text-foreground">Sidebar</code> is a full-page layout primitive
      (<code className="text-foreground">SidebarProvider</code> + <code className="text-foreground">SidebarInset</code>).
      See the code tab for a minimal shell; it themes from the <code className="text-foreground">--sidebar-*</code> tokens.
    </div>
  );

const meta = {
  title: "Navigation/Sidebar",
  parameters: {
    layout: "padded",
    docs: { source: { code: `<SidebarProvider>\n  <Sidebar>\n    <SidebarHeader>…</SidebarHeader>\n    <SidebarContent>\n      <SidebarGroup>\n        <SidebarMenu>\n          <SidebarMenuItem>\n            <SidebarMenuButton isActive>Home</SidebarMenuButton>\n          </SidebarMenuItem>\n        </SidebarMenu>\n      </SidebarGroup>\n    </SidebarContent>\n  </Sidebar>\n  <SidebarInset>\n    <SidebarTrigger />\n    {/* page content */}\n  </SidebarInset>\n</SidebarProvider>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
