/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Skeleton } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex items-center gap-3">
      <Skeleton className="size-12 rounded-full" />
      <div className="space-y-2">
        <Skeleton className="h-4 w-[200px]" />
        <Skeleton className="h-4 w-[160px]" />
      </div>
    </div>
  );

const meta = {
  title: "Foundations/Skeleton",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Skeleton className=\"size-12 rounded-full\" />\\n<Skeleton className=\"h-4 w-[200px]\" />", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
