/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Slider } from "@kinetixui/ui";

const Demo = () => <Slider defaultValue={[50]} max={100} step={1} className="w-[60%]" />;

const meta = {
  title: "Form Inputs/Slider",
  component: Slider,
  args: { disabled: false },
  argTypes: { disabled: { control: "boolean" } },
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Slider defaultValue={[50]} max={100} step={1} />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <Slider {...args} defaultValue={[50]} max={100} step={1} className="w-60" /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
