/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Button, Toaster, toast } from "@kinetixui/ui";

const Demo = () => (
    <>
      <Toaster />
      <Button variant="Outline" onClick={() => toast("Event created", { description: "Sunday, December 03 at 9:00 AM" })}>
        Show toast
      </Button>
    </>
  );

const meta = {
  title: "Feedback/Sonner",
  parameters: {
    layout: "centered",
    docs: { source: { code: "// app/layout.tsx\\n<Toaster />\\n\\n// anywhere\\ntoast(\"Event created\", { description: \"Sunday, December 03\" })", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
