/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Spinner } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex items-center gap-4">
      <Spinner size="sm" />
      <Spinner />
      <Spinner size="lg" />
    </div>
  );

const meta = {
  title: "Foundations/Spinner",
  component: Spinner,
  args: { size: "md", variant: "default" },
  argTypes: {
    size: { control: "inline-radio", options: ["sm", "md", "lg"] },
    variant: { control: "inline-radio", options: ["default", "muted", "onColor"] },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Spinner size=\"sm\" />\\n<Spinner />\\n<Spinner size=\"lg\" />", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <Spinner {...args} /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
