/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Spinner } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex items-center gap-4">
      <Spinner size="sm" />
      <Spinner />
      <Spinner size="lg" />
    </div>
  );

const meta = {
  title: "Foundations/Spinner",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Spinner size="sm" />\n<Spinner />\n<Spinner size="lg" />`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
