/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Stepper } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex w-full max-w-lg flex-col gap-8">
      <Stepper
        current={1}
        steps={[{ label: "Account" }, { label: "Profile" }, { label: "Review" }]}
      />
      <Stepper
        orientation="vertical"
        current={1}
        steps={[
          { label: "Order placed", description: "We've received your order." },
          { label: "Processing", description: "Your order is being prepared." },
          { label: "Shipped", description: "On its way to you." },
        ]}
      />
    </div>
  );

const meta = {
  title: "Navigation/Stepper",
  parameters: {
    layout: "padded",
    docs: { source: { code: "<Stepper\\n  current={1}\\n  steps={[{ label: \"Account\" }, { label: \"Profile\" }, { label: \"Review\" }]}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
