/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Card, CardContent, Label, Switch } from "@kinetixui/ui";

const Demo = () => (
    <div className="flex items-center gap-2">
      <Switch id="airplane" />
      <Label htmlFor="airplane">Airplane mode</Label>
    </div>
  );

const meta = {
  title: "Form Inputs/Switch",
  component: Switch,
  args: { disabled: false, defaultChecked: false },
  argTypes: { disabled: { control: "boolean" }, defaultChecked: { control: "boolean" } },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<div className=\"flex items-center gap-2\">\\n  <Switch id=\"airplane\" />\\n  <Label htmlFor=\"airplane\">Airplane mode</Label>\\n</div>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <Switch aria-label="Airplane mode" {...args} /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };

export const States: StoryObj<typeof meta> = { render: () => (
    <Card className="w-[22rem] max-w-full">
      <CardContent className="grid gap-4 p-6">
        {([
          ["off", "Push notifications", {}],
          ["on", "Weekly digest", { defaultChecked: true }],
          ["disabled", "SMS alerts (add a phone first)", { disabled: true }],
          ["disabled-on", "Security emails (required)", { disabled: true, defaultChecked: true }],
        ] as const).map(([key, label, props]) => (
          <div key={key} className="flex items-center justify-between gap-4">
            <Label htmlFor={`sw-${key}`}>{label}</Label>
            <Switch id={`sw-${key}`} data-kx-case={key} {...props} />
          </div>
        ))}
      </CardContent>
    </Card>
  ) };
