/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { TabBar, TabBarItem } from "@kinetixui/ui";
import { Home, Mail, Search, User } from "lucide-react";

const Demo = () => {
    const [active, setActive] = React.useState("home");
    const items = [
      { key: "home", icon: <Home />, label: "Home" },
      { key: "search", icon: <Search />, label: "Search" },
      { key: "mail", icon: <Mail />, label: "Mail", badge: 3 },
      { key: "profile", icon: <User />, label: "Profile" },
    ];
    return (
      <TabBar className="w-full max-w-sm rounded-md">
        {items.map((it) => (
          <TabBarItem key={it.key} icon={it.icon} label={it.label} badge={it.badge} active={active === it.key} onClick={() => setActive(it.key)} />
        ))}
      </TabBar>
    );
  };

const meta = {
  title: "Navigation/TabBar",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<TabBar>\\n  <TabBarItem icon={<Home />} label=\"Home\" active={tab === \"home\"} onClick={() => setTab(\"home\")} />\\n  <TabBarItem icon={<Mail />} label=\"Mail\" badge={3} active={tab === \"mail\"} onClick={() => setTab(\"mail\")} />\\n</TabBar>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
