/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { TableOfContents } from "@kinetixui/ui";

const Demo = () => (
    <TableOfContents
      className="w-full max-w-xs"
      active="props"
      items={[
        { id: "overview", label: "Overview", level: 1 },
        { id: "installation", label: "Installation", level: 1 },
        { id: "usage", label: "Usage", level: 1 },
        { id: "props", label: "Props", level: 2 },
        { id: "examples", label: "Examples", level: 2 },
      ]}
    />
  );

const meta = {
  title: "Navigation/TableOfContents",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<TableOfContents\n  active={activeId}\n  items={[{ id: "overview", label: "Overview" }, { id: "props", label: "Props", level: 2 }]}\n/>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
