/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Tag } from "@kinetixui/ui";

const Demo = () => {
    const [tags, setTags] = React.useState(["design", "tokens", "figma"]);
    return (
      <div className="flex flex-wrap items-center gap-2">
        {tags.map((t) => (
          <Tag key={t} onRemove={() => setTags((cur) => cur.filter((x) => x !== t))}>
            {t}
          </Tag>
        ))}
        <Tag variant="secondary">secondary</Tag>
        <Tag variant="destructive">destructive</Tag>
        <Tag variant="warning">warning</Tag>
        <Tag variant="outline">outline</Tag>
      </div>
    );
  };

const meta = {
  title: "Feedback/Tag",
  component: Tag,
  args: { variant: "default", children: "tag" },
  argTypes: {
    variant: { control: "select", options: ["default", "secondary", "destructive", "warning", "outline"] },
    children: { control: "text" },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Tag onRemove={() => remove(t)}>{t}</Tag>\\n<Tag variant=\"secondary\">secondary</Tag>\\n<Tag variant=\"warning\">warning</Tag>\\n<Tag variant=\"outline\">outline</Tag>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => <Tag {...args} /> };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
