/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { SegmentedControl, Timeline } from "@kinetixui/ui";

const Demo = () => (
    <Timeline
      className="w-full max-w-sm"
      items={[
        { time: "2 hours ago", title: "Deployed to production", content: "v0.9.0 shipped." },
        { time: "Yesterday", title: "Opened PR #100", content: "feat(ui): add SegmentedControl" },
        { time: "3 days ago", title: "Project created" },
      ]}
    />
  );

const meta = {
  title: "Data Display/Timeline",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Timeline\\n  items={[\\n    { time: \"2 hours ago\", title: \"Deployed to production\", content: \"v0.9.0 shipped.\" },\\n    { time: \"Yesterday\", title: \"Opened PR #100\" },\\n  ]}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
