/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Toggle } from "@kinetixui/ui";
import { Italic } from "lucide-react";

const Demo = () => (
    <Toggle aria-label="Toggle italic">
      <Italic className="size-4" />
    </Toggle>
  );

const meta = {
  title: "Controls & Actions/Toggle",
  component: Toggle,
  args: { variant: "default", size: "default" },
  argTypes: {
    variant: { control: "inline-radio", options: ["default", "outline"] },
    size: { control: "inline-radio", options: ["default", "sm", "lg"] },
  },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Toggle aria-label=\"Toggle italic\"><Italic className=\"size-4\" /></Toggle>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <Toggle {...args} aria-label="Toggle italic"><Italic className="size-4" /></Toggle>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
