/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { Toggle } from "@kinetixui/ui";
import { Italic } from "lucide-react";

const Demo = () => (
    <Toggle aria-label="Toggle italic">
      <Italic className="size-4" />
    </Toggle>
  );

const meta = {
  title: "Controls & Actions/Toggle",
  parameters: {
    layout: "centered",
    docs: { source: { code: `<Toggle aria-label="Toggle italic"><Italic className="size-4" /></Toggle>`, language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
