/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx · controls: scripts/gen-stories.mjs CONTROLS */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { ToggleGroup, ToggleGroupItem } from "@kinetixui/ui";
import { Bold, Italic, Underline } from "lucide-react";

const Demo = () => (
    <ToggleGroup type="multiple">
      <ToggleGroupItem value="bold"><Bold className="size-4" /></ToggleGroupItem>
      <ToggleGroupItem value="italic"><Italic className="size-4" /></ToggleGroupItem>
      <ToggleGroupItem value="underline"><Underline className="size-4" /></ToggleGroupItem>
    </ToggleGroup>
  );

const meta = {
  title: "Controls & Actions/ToggleGroup",
  component: ToggleGroup,
  args: { type: "multiple" },
  argTypes: { type: { control: "inline-radio", options: ["single", "multiple"] } },
  parameters: {
    layout: "centered",
    docs: { source: { code: "<ToggleGroup type=\"multiple\">\\n  <ToggleGroupItem value=\"bold\"><Bold /></ToggleGroupItem>\\n  <ToggleGroupItem value=\"italic\"><Italic /></ToggleGroupItem>\\n</ToggleGroup>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Playground: StoryObj<typeof meta> = { render: (args) => (
    <ToggleGroup {...args}>
      <ToggleGroupItem value="bold"><Bold className="size-4" /></ToggleGroupItem>
      <ToggleGroupItem value="italic"><Italic className="size-4" /></ToggleGroupItem>
      <ToggleGroupItem value="underline"><Underline className="size-4" /></ToggleGroupItem>
    </ToggleGroup>
  ) };

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
