/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button, Tour } from "@kinetixui/ui";
import { Settings } from "lucide-react";

const Demo = () => {
    const [open, setOpen] = React.useState(false);
    const [stepIndex, setStepIndex] = React.useState(0);
    return (
      <div className="flex w-full flex-col items-start gap-4">
        <Button
          size="sm"
          onClick={() => {
            setStepIndex(0);
            setOpen(true);
          }}
        >
          Start tour
        </Button>
        <div className="flex items-center gap-3">
          <Button data-tour-demo="save" variant="Outline" size="sm">
            Save
          </Button>
          <Button data-tour-demo="share" variant="Outline" size="sm">
            Share
          </Button>
          <Button data-tour-demo="settings" variant="Ghost" size="icon" aria-label="Settings">
            <Settings className="size-4" />
          </Button>
        </div>
        <Tour
          open={open}
          onOpenChange={setOpen}
          stepIndex={stepIndex}
          onStepIndexChange={setStepIndex}
          steps={[
            {
              target: '[data-tour-demo="save"]',
              title: "Save your work",
              content: "Changes save automatically, but you can force a save here.",
            },
            {
              target: '[data-tour-demo="share"]',
              title: "Invite others",
              content: "Share this project with your team.",
            },
            {
              target: '[data-tour-demo="settings"]',
              title: "Fine-tune settings",
              content: "Adjust preferences for this workspace.",
            },
          ]}
        />
      </div>
    );
  };

const meta = {
  title: "Overlays/Tour",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<Tour\\n  open={open}\\n  onOpenChange={setOpen}\\n  stepIndex={stepIndex}\\n  onStepIndexChange={setStepIndex}\\n  steps={[\\n    { target: '[data-tour=\"save\"]', title: \"Save your work\", content: \"…\" },\\n    { target: '[data-tour=\"share\"]', title: \"Invite others\", content: \"…\" },\\n  ]}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
