/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { TreeItem, TreeView } from "@kinetixui/ui";

const Demo = () => {
    const [selected, setSelected] = React.useState("button.tsx");
    return (
      <TreeView
        className="w-full max-w-xs"
        selected={selected}
        onSelectedChange={setSelected}
        defaultExpanded={["src", "src/components"]}
      >
        <TreeItem value="src" label="src">
          <TreeItem value="src/components" label="components">
            <TreeItem value="button.tsx" label="button.tsx" />
            <TreeItem value="badge.tsx" label="badge.tsx" />
          </TreeItem>
          <TreeItem value="index.ts" label="index.ts" />
        </TreeItem>
        <TreeItem value="readme" label="README.md" />
      </TreeView>
    );
  };

const meta = {
  title: "Navigation/TreeView",
  parameters: {
    layout: "centered",
    docs: { source: { code: "<TreeView selected={selected} onSelectedChange={setSelected} defaultExpanded={[\"src\"]}>\\n  <TreeItem value=\"src\" label=\"src\">\\n    <TreeItem value=\"index.ts\" label=\"index.ts\" />\\n  </TreeItem>\\n  <TreeItem value=\"readme\" label=\"README.md\" />\\n</TreeView>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
