/* AUTO-GENERATED by scripts/gen-stories.mjs — do not edit.
   Source of truth: apps/web/src/registry/demos.tsx */
import * as React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { VirtualList } from "@kinetixui/ui";

const Demo = () => {
    const rows = React.useMemo(
      () => Array.from({ length: 10000 }, (_, i) => ({ id: i, label: `Row ${i + 1}` })),
      [],
    );
    return (
      <VirtualList
        className="w-full max-w-sm rounded-md border"
        items={rows}
        itemHeight={36}
        height={280}
        getItemKey={(row) => row.id}
        renderItem={(row) => (
          <div className="flex h-full items-center border-b px-3 text-sm">{row.label}</div>
        )}
      />
    );
  };

const meta = {
  title: "Data Display/VirtualList",
  parameters: {
    layout: "centered",
    docs: { source: { code: "const rows = Array.from({ length: 10000 }, (_, i) => ({ id: i, label: \\`Row \\${i + 1}\\` }));\\n\\n<VirtualList\\n  items={rows}\\n  itemHeight={36}\\n  height={280}\\n  getItemKey={(row) => row.id}\\n  renderItem={(row) => <div>{row.label}</div>}\\n/>", language: "tsx" } },
  },
} satisfies Meta;

export default meta;

export const Default: StoryObj<typeof meta> = { render: () => <Demo /> };
