//
// KinetixColorSchemeDark — generated by Style Dictionary. Do not edit.
//

import 'dart:ui';

class KinetixColorSchemeDark {
  KinetixColorSchemeDark._();

  static const background = Color(0xFF050C11);
  static const foreground = Color(0xFFF0F7FF);
  static const card = Color(0xFF0B1821);
  static const cardForeground = Color(0xFFF0F7FF);
  static const popover = Color(0xFF0B1821);
  static const popoverForeground = Color(0xFFF0F7FF);
  static const primary = Color(0xFF92B2C8);
  static const primaryForeground = Color(0xFF050C11);
  static const secondary = Color(0xFF2E362E);
  static const secondaryForeground = Color(0xFFE3E7E3);
  static const muted = Color(0xFF102432);
  static const mutedForeground = Color(0xFF92B2C8);
  static const accent = Color(0xFF102432);
  static const accentForeground = Color(0xFFF0F7FF);
  static const destructive = Color(0xFFDD6A6A);
  static const destructiveForeground = Color(0xFF280202);
  static const success = Color(0xFF90A08F);
  static const successForeground = Color(0xFF171B17);
  static const warning = Color(0xFFFFC975);
  static const warningForeground = Color(0xFF2A1A00);
  static const border = Color(0xFF395A70);
  static const input = Color(0xFF395A70);
  static const ring = Color(0xFF92B2C8);
  static const chart1 = Color(0xFF92B2C8);
  static const chart2 = Color(0xFF90A08F);
  static const chart3 = Color(0xFFFFC975);
  static const chart4 = Color(0xFFDD6A6A);
  static const chart5 = Color(0xFFD2C1B6);
  static const sidebar = Color(0xFF0B1821);
  static const sidebarForeground = Color(0xFFF0F7FF);
  static const sidebarPrimary = Color(0xFF92B2C8);
  static const sidebarPrimaryForeground = Color(0xFF050C11);
  static const sidebarAccent = Color(0xFF102432);
  static const sidebarAccentForeground = Color(0xFFF0F7FF);
  static const sidebarBorder = Color(0xFF395A70);
  static const sidebarRing = Color(0xFF92B2C8);
  static const tertiary = Color(0xFF395A70);
  static const tertiaryForeground = Color(0xFFF0F7FF);
  static const info = Color(0xFF92B2C8);
  static const infoForeground = Color(0xFF050C11);
}
