import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { DEFAULT_PRESET, encodePreset, type PresetConfig } from "@kinetixui/create-preset";
import { guaranteedContrast } from "../color-math";
import { resolveCreateTheme } from "../resolve";
import { exportCompose } from "./compose";

/**
 * The committed Compose fixture, and what it is and is not for.
 *
 * `.github/workflows/native-compose.yml` runs `assembleDebug`, `testDebugUnitTest` and `lintDebug` on any
 * change under `packages/ui-compose/**`, so a fixture generated by this exporter and committed into the
 * Kotlin TEST source set gets compiled by the real toolchain, against the real `KinetixColors`
 * constructor. `CustomThemeTest` then installs it and reads the values back through
 * `KinetixColorScheme.current`.
 *
 * That makes it an INTEGRATION fixture: it proves the generated Kotlin compiles and that a custom theme
 * actually reaches the components. It is not the colour-space guarantee — one design proves nothing about
 * the wheel. The exhaustive guarantee lives in the shared engine's own tests, which sweep every hue and
 * every neutral in all three representations.
 *
 * What this file does is keep the committed fixture honest. A fixture that drifted from the exporter
 * would still compile, and would be testing code that no longer ships.
 */

/** The fixture's design. Generated dimensions only — a manual override can fail AA by design, and the */
/** Android side asserts the theme installs, not that an arbitrary design is readable. */
export const FIXTURE_DESIGN: PresetConfig = {
  ...DEFAULT_PRESET,
  brand: "#c2410c",
  neutral: "warm",
  chartPalette: "warm",
};

const FIXTURE_SYMBOL = "CreateThemeFixture";
const FIXTURE_PATH = "packages/ui-compose/ui/src/test/kotlin/com/kinetixui/create/CreateThemeFixture.kt";

const regenerate = [
  "The committed Compose fixture no longer matches this exporter's output, so the Android runner is",
  "compiling something the code no longer produces. Regenerate it:",
  "",
  "  pnpm --filter @kinetixui/cli build",
  `  node packages/cli/dist/index.js preset compose ${encodePreset(FIXTURE_DESIGN)} --name ${FIXTURE_SYMBOL} --output ${FIXTURE_PATH}`,
].join("\n");

describe("the committed Compose fixture", () => {
  const committed = readFileSync(new URL(`../../../../${FIXTURE_PATH}`, import.meta.url), "utf8");

  it("is byte-identical to what this exporter produces today", () => {
    expect(committed, regenerate).toBe(exportCompose(resolveCreateTheme(FIXTURE_DESIGN), { symbol: FIXTURE_SYMBOL }));
  });

  it("lives in a directory matching the package it declares", () => {
    // Kotlin does not require it, but a file in the wrong place is the kind of thing an IDE flags at a
    // consumer and nobody here ever sees.
    expect(committed).toContain("package com.kinetixui.create");
    expect(FIXTURE_PATH).toContain("kotlin/com/kinetixui/create/");
  });

  it("exercises the parts only a Kotlin compiler would catch", () => {
    // Literals in both appearances, references for the fields Create does not model, and a full chart
    // list — the three shapes the generated file can get wrong in a way only the toolchain notices.
    expect(committed).toMatch(/val light = KinetixColors\(\n\s+primary = Color\(0x/);
    expect(committed).toMatch(/val dark = KinetixColors\(\n\s+primary = Color\(0x/);
    expect(committed).toContain("secondary = KinetixTokensLight.colorSecondary,");
    expect(committed).toContain("secondary = KinetixTokensDark.colorSecondary,");
    expect(committed.match(/chart = listOf\(/g)).toHaveLength(2);
  });

  it("is a genuinely custom theme, or the Android test proves nothing", () => {
    // If the fixture resolved to the shipped values, `custom_light_colors_reach_the_components` would
    // pass while testing the default path.
    const theme = resolveCreateTheme(FIXTURE_DESIGN);
    expect(theme.meta.isDefault).toBe(false);
    expect(committed).toContain("action = Color(0xffc2410c),");
  });

  it("is installed and read back on the Android side, not merely compiled", () => {
    // If someone deletes the XCTest-equivalent, this says so — the fixture would otherwise sit in the
    // test source set compiling and asserting nothing.
    const tests = readFileSync(
      new URL("../../../ui-compose/ui/src/test/kotlin/com/kinetixui/ui/CustomThemeTest.kt", import.meta.url),
      "utf8",
    );
    expect(tests).toContain("CreateThemeFixture.light");
    expect(tests).toContain("CreateThemeFixture.dark");
    expect(tests).toContain("KinetixColorScheme.current");
  });

  it("clears AA, so a contrast failure on the Android side would be a real finding", () => {
    // Compose receives the resolved bytes exactly, so there is no representation in which this design
    // could be readable here and not there. If the native side ever disagreed, the discrepancy would be
    // in the test or the model — not something to patch in the exporter.
    const theme = resolveCreateTheme(FIXTURE_DESIGN);
    const failures: string[] = [];
    for (const mode of ["light", "dark"] as const) {
      const c = theme[mode].colors;
      for (const [bg, fg] of [
        ["action", "action-foreground"],
        ["action-hover", "action-foreground"],
        ["action-pressed", "action-foreground"],
        ["background", "foreground"],
        ["muted", "muted-foreground"],
        ["card", "card-foreground"],
      ] as const) {
        const ratio = guaranteedContrast(c[bg]!, c[fg]!);
        if (ratio < 4.5) failures.push(`${mode} ${bg}/${fg} ${ratio.toFixed(2)}`);
      }
    }
    expect(failures).toEqual([]);
  });
});
