import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { DEFAULT_PRESET, encodePreset, type PresetConfig } from "@kinetixui/create-preset";
import { guaranteedContrast } from "../color-math";
import { resolveCreateTheme } from "../resolve";
import { exportFlutter } from "./flutter";

/**
 * The committed Dart fixture, and what it is and is not for.
 *
 * `.github/workflows/native-flutter.yml` runs `flutter analyze` and `flutter test` on any change under
 * `packages/ui-flutter/**`, so a fixture generated by this exporter and committed into the package's test
 * directory gets analysed and compiled by the real toolchain, against the real `KinetixColors`
 * constructor. `custom_theme_test.dart` then installs it and reads the palette back through
 * `KinetixTheme.of(context)`.
 *
 * It is an INTEGRATION fixture: it proves the generated Dart compiles and that a custom theme reaches the
 * widgets. It is not the colour-space guarantee — one design proves nothing about the wheel. The
 * exhaustive guarantee lives in the shared engine's tests, which sweep every hue and neutral in all three
 * representations.
 *
 * What this file does is keep the committed fixture honest. A fixture that drifted from the exporter
 * would still analyse cleanly, and would be testing code that no longer ships.
 */

/** The fixture's design. Unlike the other two it carries a manual override, because Flutter's contract */
/** is complete enough that an override lands on a field rather than falling into a gap. */
export const FIXTURE_DESIGN: PresetConfig = {
  ...DEFAULT_PRESET,
  brand: "#c2410c",
  neutral: "warm",
  chartPalette: "warm",
  manualOverrides: { border: "#ff0000" },
};

const FIXTURE_SYMBOL = "CreateThemeFixture";
const FIXTURE_PATH = "packages/ui-flutter/test/generated/create_theme_fixture.dart";

const regenerate = [
  "The committed Dart fixture no longer matches this exporter's output, so the Flutter runner is",
  "analysing something the code no longer produces. Regenerate it:",
  "",
  "  pnpm --filter @kinetixui/cli build",
  `  node packages/cli/dist/index.js preset flutter ${encodePreset(FIXTURE_DESIGN)} --name ${FIXTURE_SYMBOL} --output ${FIXTURE_PATH}`,
].join("\n");

describe("the committed Dart fixture", () => {
  const committed = readFileSync(new URL(`../../../../${FIXTURE_PATH}`, import.meta.url), "utf8");

  it("is byte-identical to what this exporter produces today", () => {
    expect(committed, regenerate).toBe(exportFlutter(resolveCreateTheme(FIXTURE_DESIGN), { symbol: FIXTURE_SYMBOL }));
  });

  it("exercises the parts only the Dart toolchain would catch", () => {
    // Literals in both appearances, shipped references for the fields Create does not model, a typed
    // chart list, and an override — the shapes the generated file can get wrong in a way only `flutter
    // analyze` notices.
    expect(committed).toMatch(/static final KinetixColors light = KinetixColors\(\n\s+primary: Color\(0xFF/);
    expect(committed).toMatch(/static final KinetixColors dark = KinetixColors\(\n\s+primary: Color\(0xFF/);
    expect(committed).toContain("tertiaryForeground: KinetixColors.light.tertiaryForeground,");
    expect(committed).toContain("tertiaryForeground: KinetixColors.dark.tertiaryForeground,");
    expect(committed.match(/chart: <Color>\[/g)).toHaveLength(2);
    expect(committed).toContain("border: Color(0xFFFF0000),");
  });

  it("covers everything the brief asks a fixture to exercise", () => {
    const theme = resolveCreateTheme(FIXTURE_DESIGN);
    expect(theme.meta.isDefault).toBe(false);
    expect(FIXTURE_DESIGN.brand).not.toBe(DEFAULT_PRESET.brand); // custom brand
    expect(FIXTURE_DESIGN.neutral).not.toBe(DEFAULT_PRESET.neutral); // neutral
    expect(FIXTURE_DESIGN.chartPalette).not.toBe(DEFAULT_PRESET.chartPalette); // chart palette
    expect(Object.keys(FIXTURE_DESIGN.manualOverrides)).toHaveLength(1); // manual override
    // action states, both appearances
    for (const mode of ["light", "dark"] as const) {
      for (const token of ["action", "action-hover", "action-pressed"] as const) {
        expect(theme[mode].colors[token], `${mode} ${token}`).toMatch(/^#[0-9a-f]{6}$/);
      }
    }
  });

  it("is installed and read back on the Dart side, not merely analysed", () => {
    const tests = readFileSync(
      new URL("../../../ui-flutter/test/custom_theme_test.dart", import.meta.url),
      "utf8",
    );
    expect(tests).toContain("CreateThemeFixture.light");
    expect(tests).toContain("CreateThemeFixture.dark");
    expect(tests).toContain("KinetixTheme.of(context)");
    expect(tests).toContain("KinetixMaterialTheme.fromColors");
    expect(tests).toContain("KinetixCupertinoTheme.fromColors");
  });

  it("clears AA, so a contrast failure on the Dart side would be a real finding", () => {
    // Flutter receives the resolved bytes exactly, so there is no representation in which this design
    // could be readable here and not there. A disagreement would be in the test or the model — not
    // something to patch in the exporter.
    const theme = resolveCreateTheme(FIXTURE_DESIGN);
    const failures: string[] = [];
    for (const mode of ["light", "dark"] as const) {
      const c = theme[mode].colors;
      for (const [bg, fg] of [
        ["action", "action-foreground"],
        ["action-hover", "action-foreground"],
        ["action-pressed", "action-foreground"],
        ["background", "foreground"],
        ["muted", "muted-foreground"],
        ["card", "card-foreground"],
      ] as const) {
        const ratio = guaranteedContrast(c[bg]!, c[fg]!);
        if (ratio < 4.5) failures.push(`${mode} ${bg}/${fg} ${ratio.toFixed(2)}`);
      }
    }
    expect(failures).toEqual([]);
  });
});
