import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { DEFAULT_PRESET, encodePreset, type PresetConfig } from "@kinetixui/create-preset";
import { contrastRatio } from "../color-math";
import { resolveCreateTheme } from "../resolve";
import { exportSwiftUi } from "./swiftui";

/**
 * The pairs `ContrastTests.assertGeneratedAA` runs over the fixture, in its order.
 *
 * Everything `check:contrast` holds the shipped theme to, except `brand / background` — `brand` is the
 * user's colour unclamped so a dark brand keeps its identity, and `brand-foreground` on `brand` is the
 * pair that actually carries text. The action foreground on `action-hover` and `action-pressed` is in
 * this list: it used to fail, the engine was fixed, and it is asserted rather than excused.
 */
const SWIFT_ASSERTED_PAIRS: [fg: string, bg: string][] = [
  ["foreground", "background"],
  ["card-foreground", "card"],
  ["popover-foreground", "popover"],
  ["primary-foreground", "primary"],
  ["secondary-foreground", "secondary"],
  ["muted-foreground", "muted"],
  ["muted-foreground", "background"],
  ["accent-foreground", "accent"],
  ["destructive-foreground", "destructive"],
  ["action-foreground", "action"],
  ["action-foreground", "action-hover"],
  ["action-foreground", "action-pressed"],
  ["brand-foreground", "brand"],
];

/**
 * The only real proof that this exporter emits Swift.
 *
 * TypeScript cannot tell whether a string it built is valid Swift, and this machine has no Swift
 * toolchain — but `.github/workflows/native-swiftui.yml` runs `swift build` and `swift test` on a macOS
 * runner for any change under `packages/ui-swiftui/**`. So a fixture generated by this exporter is
 * committed into the Swift TEST TARGET: the compiler type-checks every one of its 70 arguments against
 * `KinetixColors`' real initializer, and `ContrastTests` then runs WCAG AA over the result.
 *
 * That makes the claim "the output compiles" something CI establishes rather than something this file
 * asserts. What this file does is keep the committed fixture honest — a fixture that drifted from the
 * exporter would still compile, and would prove nothing about the code that ships.
 */

/** The fixture's design. Generated dimensions only: a manual override could fail AA by design, and the */
/** point of the Swift-side check is that an exported theme the ENGINE produced clears the bar. */
export const FIXTURE_DESIGN: PresetConfig = {
  ...DEFAULT_PRESET,
  brand: "#c2410c",
  neutral: "warm",
  chartPalette: "warm",
};

const FIXTURE_SYMBOL = "CreateThemeFixture";
const FIXTURE_PATH = "packages/ui-swiftui/Tests/KinetixUITests/Generated/CreateThemeFixture.swift";

const regenerate = [
  "The committed Swift fixture no longer matches this exporter's output, so the macOS runner is",
  "compiling something the code no longer produces. Regenerate it:",
  "",
  `  pnpm --filter @kinetixui/cli build`,
  `  node packages/cli/dist/index.js preset swiftui ${encodePreset(FIXTURE_DESIGN)} --name ${FIXTURE_SYMBOL} --output ${FIXTURE_PATH}`,
].join("\n");

describe("the committed Swift fixture", () => {
  const committed = readFileSync(new URL(`../../../../${FIXTURE_PATH}`, import.meta.url), "utf8");

  it("is byte-identical to what this exporter produces today", () => {
    expect(committed, regenerate).toBe(exportSwiftUi(resolveCreateTheme(FIXTURE_DESIGN), { symbol: FIXTURE_SYMBOL }));
  });

  it("exercises the parts a compiler would catch", () => {
    // Literals in both appearances, references for the fields Create does not model, and a full chart
    // array — the three shapes the generated file can get wrong in a way only Swift would notice.
    expect(committed).toMatch(/light = KinetixColors\(\n\s+primary: Color\(red:/);
    expect(committed).toMatch(/dark = KinetixColors\(\n\s+primary: Color\(red:/);
    expect(committed).toContain("tertiary: KinetixColorsSwiftUI.tertiary,");
    expect(committed).toContain("tertiary: KinetixColorsSwiftUIDark.tertiary,");
    expect(committed.match(/chart: \[/g)).toHaveLength(2);
  });

  it("clears every pair the Swift-side suite will check it against", () => {
    // `ContrastTests.assertGeneratedAA` runs these on the macOS runner. Computing them here too means a
    // fixture that would fail there fails in this repo's ordinary test run first, minutes rather than a
    // CI round-trip earlier — and it keeps the two lists honest about being the same list.
    const theme = resolveCreateTheme(FIXTURE_DESIGN);
    const failures: string[] = [];
    for (const mode of ["light", "dark"] as const) {
      const colors = theme[mode].colors;
      for (const [fg, bg] of SWIFT_ASSERTED_PAIRS) {
        const ratio = contrastRatio(colors[bg]!, colors[fg]!);
        if (ratio < 4.5) failures.push(`${mode} ${fg}/${bg} ${ratio.toFixed(2)}`);
      }
    }
    expect(failures).toEqual([]);
  });

  it("checks the same pairs the Swift file lists, and no more", () => {
    // If someone widens the Swift list, this says so — the narrower set is a deliberate statement about
    // what the engine guarantees, not an oversight, and the reasoning lives in ContrastTests.swift.
    const source = readFileSync(
      new URL("../../../ui-swiftui/Tests/KinetixUITests/ContrastTests.swift", import.meta.url),
      "utf8",
    );
    const block = source.slice(source.indexOf("private let generatedPairs"), source.indexOf("private func assertGeneratedAA"));
    const listed = [...block.matchAll(/\\\.([a-zA-Z]+), \\\.([a-zA-Z]+)\)/g)].map((m) => `${m[1]}/${m[2]}`);
    const camel = (t: string) => t.replace(/[-_]([a-z0-9])/g, (_, c: string) => c.toUpperCase());

    expect(listed).toEqual(SWIFT_ASSERTED_PAIRS.map(([fg, bg]) => `${camel(fg)}/${camel(bg)}`));
  });

  it("is checked for contrast on the Swift side, not only here", () => {
    // If someone removes the XCTest that does it, this says so — the fixture would otherwise sit in the
    // test target compiling and asserting nothing.
    const tests = readFileSync(
      new URL("../../../ui-swiftui/Tests/KinetixUITests/ContrastTests.swift", import.meta.url),
      "utf8",
    );
    expect(tests).toContain(`${FIXTURE_SYMBOL}.light`);
    expect(tests).toContain(`${FIXTURE_SYMBOL}.dark`);
  });
});
